-- Set schema
SET SCHEMA "PUBLIC";

-- Drop tables in reverse order of creation
DROP TABLE IF EXISTS "TICKET_RESERVATION" CASCADE;
DROP TABLE IF EXISTS "SEAT" CASCADE;
DROP TABLE IF EXISTS "SESSION_EVENT" CASCADE;
DROP TABLE IF EXISTS "TARIFICATION" CASCADE;
DROP TABLE IF EXISTS "PAYMENT" CASCADE;
DROP TABLE IF EXISTS "HALL" CASCADE;
DROP TABLE IF EXISTS "EVENT" CASCADE;
DROP TABLE IF EXISTS "EMPLOYEE" CASCADE;
DROP TABLE IF EXISTS "CUSTOMER" CASCADE;
DROP TABLE IF EXISTS "CONFIGURATION_HALL" CASCADE;
DROP TABLE IF EXISTS "CATEGORY_TARIFF" CASCADE;
DROP TABLE IF EXISTS "CATEGORY_SPATIAL" CASCADE;
DROP TABLE IF EXISTS "BOOKING" CASCADE;
DROP TABLE IF EXISTS "PAYMENT_STATUS" CASCADE;
DROP TABLE IF EXISTS "SEAT_STATUS" CASCADE;
DROP TABLE IF EXISTS "VENUE" CASCADE;
