DROP TABLE IF EXISTS BOOKING;

CREATE TABLE BOOKING(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BOOKING_CREATION_TIMESTAMP TIMESTAMP(6),
    TOTAL_PRICE_HT FLOAT(53) NOT NULL,
    CUSTOMER_FK BIGINT
);

DROP TABLE IF EXISTS CATEGORY_SPATIAL;

CREATE TABLE CATEGORY_SPATIAL(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME CHARACTER VARYING(50) NOT NULL
);

DROP TABLE IF EXISTS CATEGORY_TARIFF;

CREATE TABLE CATEGORY_TARIFF(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME CHARACTER VARYING(50) NOT NULL,
    TARIFICATION_FK BIGINT NOT NULL
);

DROP TABLE IF EXISTS CONFIGURATION_HALL;

CREATE TABLE CONFIGURATION_HALL(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CAPACITY_OF_CONFIGURATION INTEGER NOT NULL,
    NAME CHARACTER VARYING(255),
    HALL_FK BIGINT NOT NULL
);

DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CITY CHARACTER VARYING(255),
    COUNTRY CHARACTER VARYING(255),
    STREET CHARACTER VARYING(255),
    ZIPCODE CHARACTER VARYING(255),
    CREDIT_CARD_NUMBER CHARACTER VARYING(255),
    EMAIL CHARACTER VARYING(255),
    FIRST_NAME CHARACTER VARYING(255),
    LAST_NAME CHARACTER VARYING(255),
    PHONE_NUMBER CHARACTER VARYING(255),
    USERNAME CHARACTER VARYING(255)
);

DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL CHARACTER VARYING(255) NOT NULL,
    PASSWORD CHARACTER VARYING(255) NOT NULL,
    USERNAME CHARACTER VARYING(255) NOT NULL,
    VENUE_FK BIGINT
);

DROP TABLE IF EXISTS EVENT;

CREATE TABLE EVENT(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CLOSED_DAY CHARACTER VARYING(255),
    DATE_END DATE,
    DATE_START DATE,
    DESCRIPTION CHARACTER VARYING(255),
    NAME CHARACTER VARYING(255)
);

DROP TABLE IF EXISTS HALL;

CREATE TABLE HALL(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CAPACITY_OF_HALL INTEGER NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL,
    VENUE_FK BIGINT NOT NULL
);

DROP TABLE IF EXISTS PAYMENT;

CREATE TABLE PAYMENT(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_DATE_TIME TIMESTAMP(6),
    BOOKING_FK BIGINT,
    PAYMENT_STATUS_CATEGORY_FK BIGINT
);

DROP TABLE IF EXISTS PAYMENT_STATUS;

CREATE TABLE PAYMENT_STATUS(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_STATUS_NAME CHARACTER VARYING(255)
);

DROP TABLE IF EXISTS SEAT;

CREATE TABLE SEAT(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    IS_SEATED BOOLEAN NOT NULL,
    ROW_NO CHARACTER(1) NOT NULL,
    SEAT_NO INTEGER NOT NULL,
    CATEGORY_SPATIAL_FK BIGINT,
    CATEGORY_TARIFF_FK BIGINT,
    CONFIGURATION_HALL_FK BIGINT,
    SEAT_STATUS_FK BIGINT
);

DROP TABLE IF EXISTS SEAT_STATUS;

CREATE TABLE SEAT_STATUS(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME CHARACTER VARYING(50) NOT NULL
);

DROP TABLE IF EXISTS SESSION_EVENT;

CREATE TABLE SESSION_EVENT(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATE_AND_TIME_END_SESSION_EVENT TIMESTAMP(6),
    DATE_AND_TIME_START_SESSION_EVENT TIMESTAMP(6),
    DURATION_IN_MINUTES INTEGER NOT NULL,
    CONFIGURATION_HALL_FK BIGINT NOT NULL,
    EVENT_FK BIGINT NOT NULL
);

DROP TABLE IF EXISTS TARIFICATION;

CREATE TABLE TARIFICATION(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BASE_PRICE FLOAT(53) NOT NULL,
    DISCOUNT_CHILD_RATE FLOAT(53) NOT NULL,
    DISCOUNT_SENIOR_RATE FLOAT(53) NOT NULL,
    DISCOUNT_STUDENT_RATE FLOAT(53) NOT NULL,
    DISCOUNT_UNEMPLOYED_RATE FLOAT(53) NOT NULL,
    TAXE_RATE FLOAT(53) NOT NULL,
    EVENT_FK BIGINT NOT NULL
);

DROP TABLE IF EXISTS TICKET_RESERVATION;

CREATE TABLE TICKET_RESERVATION(
    IS_BOOKED BOOLEAN NOT NULL,
    SESSION_EVENT_ID BIGINT NOT NULL,
    SEAT_ID BIGINT NOT NULL,
    BOOKING_FK BIGINT
);

ALTER TABLE
    TICKET_RESERVATION
ADD
    CONSTRAINT CONSTRAINT_FE PRIMARY KEY(SEAT_ID, SESSION_EVENT_ID);

DROP TABLE IF EXISTS VENUE;

CREATE TABLE VENUE(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CITY CHARACTER VARYING(255),
    COUNTRY CHARACTER VARYING(255),
    STREET CHARACTER VARYING(255),
    ZIPCODE CHARACTER VARYING(255),
    NAME CHARACTER VARYING(50) NOT NULL
);

ALTER TABLE
    SEAT_STATUS
ADD
    CONSTRAINT UK_1SW6OLYIO0P1BLGJ7QIE1AE8J UNIQUE(NAME);

ALTER TABLE
    CATEGORY_SPATIAL
ADD
    CONSTRAINT UK_Q9H32GMJG3TJN0XR20PHQOU4A UNIQUE(NAME);

ALTER TABLE
    VENUE
ADD
    CONSTRAINT UK_9UYUOC3VS9LV1QPAE6J8Q40XE UNIQUE(NAME);

ALTER TABLE
    CATEGORY_TARIFF
ADD
    CONSTRAINT UK_21PI7S8J5CEUJAEN5NUN0HRML UNIQUE(NAME);

ALTER TABLE
    SEAT
ADD
    CONSTRAINT FKPO6A28I5TSA019W77SDRVXBLX FOREIGN KEY(CATEGORY_TARIFF_FK) REFERENCES CATEGORY_TARIFF(ID);

ALTER TABLE
    SESSION_EVENT
ADD
    CONSTRAINT FKGOVXY4CFT2JDVQOJV2K9MIET4 FOREIGN KEY(EVENT_FK) REFERENCES EVENT(ID);

ALTER TABLE
    SEAT
ADD
    CONSTRAINT FKLE9T8YNL1VVBJDCEHRKL4UAGR FOREIGN KEY(SEAT_STATUS_FK) REFERENCES SEAT_STATUS(ID);

ALTER TABLE
    TICKET_RESERVATION
ADD
    CONSTRAINT FKEKDBVXMS2LP50COXYBFCMCFRK FOREIGN KEY(BOOKING_FK) REFERENCES BOOKING(ID);

ALTER TABLE
    TICKET_RESERVATION
ADD
    CONSTRAINT FKA69VJO0BFCI6GEGXTWVDVBO7 FOREIGN KEY(SESSION_EVENT_ID) REFERENCES SESSION_EVENT(ID);

ALTER TABLE
    TICKET_RESERVATION
ADD
    CONSTRAINT FKH15E523TLLF8PJ3TV17E6STUA FOREIGN KEY(SEAT_ID) REFERENCES SEAT(ID);

ALTER TABLE
    CONFIGURATION_HALL
ADD
    CONSTRAINT FK30PXI0YTIEY7U8YJK001XUMYX FOREIGN KEY(HALL_FK) REFERENCES HALL(ID);

ALTER TABLE
    SESSION_EVENT
ADD
    CONSTRAINT FKDVP6OJAQ6IERHYDAT1RUKO5TS FOREIGN KEY(CONFIGURATION_HALL_FK) REFERENCES CONFIGURATION_HALL(ID);

ALTER TABLE
    PAYMENT
ADD
    CONSTRAINT FKT2ST7E5O97IE1KPQMMBJM8TBI FOREIGN KEY(PAYMENT_STATUS_CATEGORY_FK) REFERENCES PAYMENT_STATUS(ID);

ALTER TABLE
    PAYMENT
ADD
    CONSTRAINT FKR6U1DTNIFMYBIHROMPM8H39NT FOREIGN KEY(BOOKING_FK) REFERENCES BOOKING(ID);

ALTER TABLE
    CATEGORY_TARIFF
ADD
    CONSTRAINT FK7GDPKE50VTKIO0DTKHWQOXLM5 FOREIGN KEY(TARIFICATION_FK) REFERENCES TARIFICATION(ID);

ALTER TABLE
    TARIFICATION
ADD
    CONSTRAINT FK1HS81DWRUCERR9F7ED6RWCYDY FOREIGN KEY(EVENT_FK) REFERENCES EVENT(ID);

ALTER TABLE
    HALL
ADD
    CONSTRAINT FKN59VGUK8D46MGHVJB86DA7EI8 FOREIGN KEY(VENUE_FK) REFERENCES VENUE(ID);

ALTER TABLE
    EMPLOYEE
ADD
    CONSTRAINT FKSAED0NWBUXI1R5HTM832PR2AP FOREIGN KEY(VENUE_FK) REFERENCES VENUE(ID);

ALTER TABLE
    SEAT
ADD
    CONSTRAINT FKEO7XH62Y5VH3ENV2FBG63OW5V FOREIGN KEY(CATEGORY_SPATIAL_FK) REFERENCES CATEGORY_SPATIAL(ID);

ALTER TABLE
    SEAT
ADD
    CONSTRAINT FK8KGFJ660L8PIPC8FJ0UYUGCKF FOREIGN KEY(CONFIGURATION_HALL_FK) REFERENCES CONFIGURATION_HALL(ID);

ALTER TABLE
    BOOKING
ADD
    CONSTRAINT FKRUQPR11M0SKN17EC53SYUNDLR FOREIGN KEY(CUSTOMER_FK) REFERENCES CUSTOMER(ID);