/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionModelObject,
  CollectionModelTicketReservation,
  EntityModelCustomer,
} from '../models/index';
import {
    CollectionModelObjectFromJSON,
    CollectionModelObjectToJSON,
    CollectionModelTicketReservationFromJSON,
    CollectionModelTicketReservationToJSON,
    EntityModelCustomerFromJSON,
    EntityModelCustomerToJSON,
} from '../models/index';

export interface CreatePropertyReferenceBookingPatchRequest {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface CreatePropertyReferenceBookingPatch1Request {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface CreatePropertyReferenceBookingPutRequest {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface CreatePropertyReferenceBookingPut1Request {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface DeletePropertyReferenceBookingDeleteRequest {
    id: string;
}

export interface DeletePropertyReferenceBookingDelete1Request {
    id: string;
}

export interface DeletePropertyReferenceIdBookingDeleteRequest {
    id: string;
    propertyId: string;
}

export interface DeletePropertyReferenceIdBookingDelete1Request {
    id: string;
    propertyId: string;
}

export interface FollowPropertyReferenceBookingGetRequest {
    id: string;
    propertyId: string;
}

export interface FollowPropertyReferenceBookingGet1Request {
    id: string;
}

export interface FollowPropertyReferenceBookingGet2Request {
    id: string;
    propertyId: string;
}

export interface FollowPropertyReferenceBookingGet21Request {
    id: string;
}

/**
 * 
 */
export class BookingPropertyReferenceControllerApi extends runtime.BaseAPI {

    /**
     * patch-customer-by-booking-Id
     */
    async createPropertyReferenceBookingPatchRaw(requestParameters: CreatePropertyReferenceBookingPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelCustomer>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceBookingPatch().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceBookingPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/bookings/{id}/customer`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelCustomerFromJSON(jsonValue));
    }

    /**
     * patch-customer-by-booking-Id
     */
    async createPropertyReferenceBookingPatch(requestParameters: CreatePropertyReferenceBookingPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelCustomer | null | undefined > {
        const response = await this.createPropertyReferenceBookingPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * patch-ticketreservation-by-booking-Id
     */
    async createPropertyReferenceBookingPatch1Raw(requestParameters: CreatePropertyReferenceBookingPatch1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelTicketReservation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceBookingPatch1().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceBookingPatch1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/bookings/{id}/reservations`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelTicketReservationFromJSON(jsonValue));
    }

    /**
     * patch-ticketreservation-by-booking-Id
     */
    async createPropertyReferenceBookingPatch1(requestParameters: CreatePropertyReferenceBookingPatch1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelTicketReservation | null | undefined > {
        const response = await this.createPropertyReferenceBookingPatch1Raw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * update-customer-by-booking-Id
     */
    async createPropertyReferenceBookingPutRaw(requestParameters: CreatePropertyReferenceBookingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelCustomer>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceBookingPut().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceBookingPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/bookings/{id}/customer`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelCustomerFromJSON(jsonValue));
    }

    /**
     * update-customer-by-booking-Id
     */
    async createPropertyReferenceBookingPut(requestParameters: CreatePropertyReferenceBookingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelCustomer | null | undefined > {
        const response = await this.createPropertyReferenceBookingPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * update-ticketreservation-by-booking-Id
     */
    async createPropertyReferenceBookingPut1Raw(requestParameters: CreatePropertyReferenceBookingPut1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelTicketReservation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceBookingPut1().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceBookingPut1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/bookings/{id}/reservations`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelTicketReservationFromJSON(jsonValue));
    }

    /**
     * update-ticketreservation-by-booking-Id
     */
    async createPropertyReferenceBookingPut1(requestParameters: CreatePropertyReferenceBookingPut1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelTicketReservation | null | undefined > {
        const response = await this.createPropertyReferenceBookingPut1Raw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * delete-customer-by-booking-Id
     */
    async deletePropertyReferenceBookingDeleteRaw(requestParameters: DeletePropertyReferenceBookingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceBookingDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/{id}/customer`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-customer-by-booking-Id
     */
    async deletePropertyReferenceBookingDelete(requestParameters: DeletePropertyReferenceBookingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceBookingDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * delete-ticketreservation-by-booking-Id
     */
    async deletePropertyReferenceBookingDelete1Raw(requestParameters: DeletePropertyReferenceBookingDelete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceBookingDelete1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/{id}/reservations`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-ticketreservation-by-booking-Id
     */
    async deletePropertyReferenceBookingDelete1(requestParameters: DeletePropertyReferenceBookingDelete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceBookingDelete1Raw(requestParameters, initOverrides);
    }

    /**
     * delete-customer-by-booking-Id
     */
    async deletePropertyReferenceIdBookingDeleteRaw(requestParameters: DeletePropertyReferenceIdBookingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceIdBookingDelete().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling deletePropertyReferenceIdBookingDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/{id}/customer/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-customer-by-booking-Id
     */
    async deletePropertyReferenceIdBookingDelete(requestParameters: DeletePropertyReferenceIdBookingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceIdBookingDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * delete-ticketreservation-by-booking-Id
     */
    async deletePropertyReferenceIdBookingDelete1Raw(requestParameters: DeletePropertyReferenceIdBookingDelete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceIdBookingDelete1().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling deletePropertyReferenceIdBookingDelete1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/{id}/reservations/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-ticketreservation-by-booking-Id
     */
    async deletePropertyReferenceIdBookingDelete1(requestParameters: DeletePropertyReferenceIdBookingDelete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceIdBookingDelete1Raw(requestParameters, initOverrides);
    }

    /**
     * get-customer-by-booking-Id
     */
    async followPropertyReferenceBookingGetRaw(requestParameters: FollowPropertyReferenceBookingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelCustomer>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceBookingGet().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling followPropertyReferenceBookingGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/{id}/customer/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelCustomerFromJSON(jsonValue));
    }

    /**
     * get-customer-by-booking-Id
     */
    async followPropertyReferenceBookingGet(requestParameters: FollowPropertyReferenceBookingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelCustomer> {
        const response = await this.followPropertyReferenceBookingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-customer-by-booking-Id
     */
    async followPropertyReferenceBookingGet1Raw(requestParameters: FollowPropertyReferenceBookingGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelCustomer>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceBookingGet1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/{id}/customer`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelCustomerFromJSON(jsonValue));
    }

    /**
     * get-customer-by-booking-Id
     */
    async followPropertyReferenceBookingGet1(requestParameters: FollowPropertyReferenceBookingGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelCustomer> {
        const response = await this.followPropertyReferenceBookingGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-ticketreservation-by-booking-Id
     */
    async followPropertyReferenceBookingGet2Raw(requestParameters: FollowPropertyReferenceBookingGet2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelTicketReservation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceBookingGet2().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling followPropertyReferenceBookingGet2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/{id}/reservations/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelTicketReservationFromJSON(jsonValue));
    }

    /**
     * get-ticketreservation-by-booking-Id
     */
    async followPropertyReferenceBookingGet2(requestParameters: FollowPropertyReferenceBookingGet2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelTicketReservation> {
        const response = await this.followPropertyReferenceBookingGet2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-ticketreservation-by-booking-Id
     */
    async followPropertyReferenceBookingGet21Raw(requestParameters: FollowPropertyReferenceBookingGet21Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelTicketReservation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceBookingGet21().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/{id}/reservations`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelTicketReservationFromJSON(jsonValue));
    }

    /**
     * get-ticketreservation-by-booking-Id
     */
    async followPropertyReferenceBookingGet21(requestParameters: FollowPropertyReferenceBookingGet21Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelTicketReservation> {
        const response = await this.followPropertyReferenceBookingGet21Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
