/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookingRequestBody,
  EntityModelBooking,
  PagedModelEntityModelBooking,
} from '../models/index';
import {
    BookingRequestBodyFromJSON,
    BookingRequestBodyToJSON,
    EntityModelBookingFromJSON,
    EntityModelBookingToJSON,
    PagedModelEntityModelBookingFromJSON,
    PagedModelEntityModelBookingToJSON,
} from '../models/index';

export interface DeleteItemResourceBookingDeleteRequest {
    id: string;
}

export interface GetCollectionResourceBookingGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceBookingGetRequest {
    id: string;
}

export interface PatchItemResourceBookingPatchRequest {
    id: string;
    bookingRequestBody: BookingRequestBody;
}

export interface PostCollectionResourceBookingPostRequest {
    bookingRequestBody: BookingRequestBody;
}

export interface PutItemResourceBookingPutRequest {
    id: string;
    bookingRequestBody: BookingRequestBody;
}

/**
 * 
 */
export class BookingEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-booking
     */
    async deleteItemResourceBookingDeleteRaw(requestParameters: DeleteItemResourceBookingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceBookingDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-booking
     */
    async deleteItemResourceBookingDelete(requestParameters: DeleteItemResourceBookingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceBookingDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-booking
     */
    async getCollectionResourceBookingGet1Raw(requestParameters: GetCollectionResourceBookingGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelBooking>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelBookingFromJSON(jsonValue));
    }

    /**
     * get-booking
     */
    async getCollectionResourceBookingGet1(requestParameters: GetCollectionResourceBookingGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelBooking> {
        const response = await this.getCollectionResourceBookingGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-booking
     */
    async getItemResourceBookingGetRaw(requestParameters: GetItemResourceBookingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelBooking>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceBookingGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelBookingFromJSON(jsonValue));
    }

    /**
     * get-booking
     */
    async getItemResourceBookingGet(requestParameters: GetItemResourceBookingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelBooking> {
        const response = await this.getItemResourceBookingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-booking
     */
    async patchItemResourceBookingPatchRaw(requestParameters: PatchItemResourceBookingPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelBooking>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceBookingPatch().'
            );
        }

        if (requestParameters['bookingRequestBody'] == null) {
            throw new runtime.RequiredError(
                'bookingRequestBody',
                'Required parameter "bookingRequestBody" was null or undefined when calling patchItemResourceBookingPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/bookings/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BookingRequestBodyToJSON(requestParameters['bookingRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelBookingFromJSON(jsonValue));
    }

    /**
     * patch-booking
     */
    async patchItemResourceBookingPatch(requestParameters: PatchItemResourceBookingPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelBooking | null | undefined > {
        const response = await this.patchItemResourceBookingPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-booking
     */
    async postCollectionResourceBookingPostRaw(requestParameters: PostCollectionResourceBookingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelBooking>> {
        if (requestParameters['bookingRequestBody'] == null) {
            throw new runtime.RequiredError(
                'bookingRequestBody',
                'Required parameter "bookingRequestBody" was null or undefined when calling postCollectionResourceBookingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/bookings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookingRequestBodyToJSON(requestParameters['bookingRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelBookingFromJSON(jsonValue));
    }

    /**
     * create-booking
     */
    async postCollectionResourceBookingPost(requestParameters: PostCollectionResourceBookingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelBooking> {
        const response = await this.postCollectionResourceBookingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-booking
     */
    async putItemResourceBookingPutRaw(requestParameters: PutItemResourceBookingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelBooking>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceBookingPut().'
            );
        }

        if (requestParameters['bookingRequestBody'] == null) {
            throw new runtime.RequiredError(
                'bookingRequestBody',
                'Required parameter "bookingRequestBody" was null or undefined when calling putItemResourceBookingPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/bookings/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BookingRequestBodyToJSON(requestParameters['bookingRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelBookingFromJSON(jsonValue));
    }

    /**
     * update-booking
     */
    async putItemResourceBookingPut(requestParameters: PutItemResourceBookingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelBooking | null | undefined > {
        const response = await this.putItemResourceBookingPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
