/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Customer,
  EntityModelBooking,
  TicketReservation,
} from '../models/index';
import {
    CustomerFromJSON,
    CustomerToJSON,
    EntityModelBookingFromJSON,
    EntityModelBookingToJSON,
    TicketReservationFromJSON,
    TicketReservationToJSON,
} from '../models/index';

export interface ExecuteSearchBookingGetRequest {
    customer?: Customer;
    ticketReservation?: TicketReservation;
}

/**
 * 
 */
export class BookingSearchControllerApi extends runtime.BaseAPI {

    /**
     */
    async executeSearchBookingGetRaw(requestParameters: ExecuteSearchBookingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelBooking>> {
        const queryParameters: any = {};

        if (requestParameters['customer'] != null) {
            queryParameters['customer'] = requestParameters['customer'];
        }

        if (requestParameters['ticketReservation'] != null) {
            queryParameters['ticketReservation'] = requestParameters['ticketReservation'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookings/search/findByCustomerAndReservations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelBookingFromJSON(jsonValue));
    }

    /**
     */
    async executeSearchBookingGet(requestParameters: ExecuteSearchBookingGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelBooking> {
        const response = await this.executeSearchBookingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
