/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CategorySpatialRequestBody,
  EntityModelCategorySpatial,
  PagedModelEntityModelCategorySpatial,
} from '../models/index';
import {
    CategorySpatialRequestBodyFromJSON,
    CategorySpatialRequestBodyToJSON,
    EntityModelCategorySpatialFromJSON,
    EntityModelCategorySpatialToJSON,
    PagedModelEntityModelCategorySpatialFromJSON,
    PagedModelEntityModelCategorySpatialToJSON,
} from '../models/index';

export interface DeleteItemResourceCategoryspatialDeleteRequest {
    id: string;
}

export interface GetCollectionResourceCategoryspatialGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceCategoryspatialGetRequest {
    id: string;
}

export interface PatchItemResourceCategoryspatialPatchRequest {
    id: string;
    categorySpatialRequestBody: CategorySpatialRequestBody;
}

export interface PostCollectionResourceCategoryspatialPostRequest {
    categorySpatialRequestBody: CategorySpatialRequestBody;
}

export interface PutItemResourceCategoryspatialPutRequest {
    id: string;
    categorySpatialRequestBody: CategorySpatialRequestBody;
}

/**
 * 
 */
export class CategorySpatialEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-categoryspatial
     */
    async deleteItemResourceCategoryspatialDeleteRaw(requestParameters: DeleteItemResourceCategoryspatialDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceCategoryspatialDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/categorySpatials/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-categoryspatial
     */
    async deleteItemResourceCategoryspatialDelete(requestParameters: DeleteItemResourceCategoryspatialDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceCategoryspatialDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-categoryspatial
     */
    async getCollectionResourceCategoryspatialGet1Raw(requestParameters: GetCollectionResourceCategoryspatialGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelCategorySpatial>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/categorySpatials`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelCategorySpatialFromJSON(jsonValue));
    }

    /**
     * get-categoryspatial
     */
    async getCollectionResourceCategoryspatialGet1(requestParameters: GetCollectionResourceCategoryspatialGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelCategorySpatial> {
        const response = await this.getCollectionResourceCategoryspatialGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-categoryspatial
     */
    async getItemResourceCategoryspatialGetRaw(requestParameters: GetItemResourceCategoryspatialGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelCategorySpatial>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceCategoryspatialGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/categorySpatials/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelCategorySpatialFromJSON(jsonValue));
    }

    /**
     * get-categoryspatial
     */
    async getItemResourceCategoryspatialGet(requestParameters: GetItemResourceCategoryspatialGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelCategorySpatial> {
        const response = await this.getItemResourceCategoryspatialGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-categoryspatial
     */
    async patchItemResourceCategoryspatialPatchRaw(requestParameters: PatchItemResourceCategoryspatialPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelCategorySpatial>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceCategoryspatialPatch().'
            );
        }

        if (requestParameters['categorySpatialRequestBody'] == null) {
            throw new runtime.RequiredError(
                'categorySpatialRequestBody',
                'Required parameter "categorySpatialRequestBody" was null or undefined when calling patchItemResourceCategoryspatialPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/categorySpatials/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CategorySpatialRequestBodyToJSON(requestParameters['categorySpatialRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelCategorySpatialFromJSON(jsonValue));
    }

    /**
     * patch-categoryspatial
     */
    async patchItemResourceCategoryspatialPatch(requestParameters: PatchItemResourceCategoryspatialPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelCategorySpatial | null | undefined > {
        const response = await this.patchItemResourceCategoryspatialPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-categoryspatial
     */
    async postCollectionResourceCategoryspatialPostRaw(requestParameters: PostCollectionResourceCategoryspatialPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelCategorySpatial>> {
        if (requestParameters['categorySpatialRequestBody'] == null) {
            throw new runtime.RequiredError(
                'categorySpatialRequestBody',
                'Required parameter "categorySpatialRequestBody" was null or undefined when calling postCollectionResourceCategoryspatialPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/categorySpatials`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CategorySpatialRequestBodyToJSON(requestParameters['categorySpatialRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelCategorySpatialFromJSON(jsonValue));
    }

    /**
     * create-categoryspatial
     */
    async postCollectionResourceCategoryspatialPost(requestParameters: PostCollectionResourceCategoryspatialPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelCategorySpatial> {
        const response = await this.postCollectionResourceCategoryspatialPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-categoryspatial
     */
    async putItemResourceCategoryspatialPutRaw(requestParameters: PutItemResourceCategoryspatialPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelCategorySpatial>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceCategoryspatialPut().'
            );
        }

        if (requestParameters['categorySpatialRequestBody'] == null) {
            throw new runtime.RequiredError(
                'categorySpatialRequestBody',
                'Required parameter "categorySpatialRequestBody" was null or undefined when calling putItemResourceCategoryspatialPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/categorySpatials/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CategorySpatialRequestBodyToJSON(requestParameters['categorySpatialRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelCategorySpatialFromJSON(jsonValue));
    }

    /**
     * update-categoryspatial
     */
    async putItemResourceCategoryspatialPut(requestParameters: PutItemResourceCategoryspatialPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelCategorySpatial | null | undefined > {
        const response = await this.putItemResourceCategoryspatialPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
