/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionModelObject,
  EntityModelHall,
} from '../models/index';
import {
    CollectionModelObjectFromJSON,
    CollectionModelObjectToJSON,
    EntityModelHallFromJSON,
    EntityModelHallToJSON,
} from '../models/index';

export interface CreatePropertyReferenceConfigurationhallPatchRequest {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface CreatePropertyReferenceConfigurationhallPutRequest {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface DeletePropertyReferenceConfigurationhallDeleteRequest {
    id: string;
}

export interface DeletePropertyReferenceIdConfigurationhallDeleteRequest {
    id: string;
    propertyId: string;
}

export interface FollowPropertyReferenceConfigurationhallGetRequest {
    id: string;
    propertyId: string;
}

export interface FollowPropertyReferenceConfigurationhallGet1Request {
    id: string;
}

/**
 * 
 */
export class ConfigurationHallPropertyReferenceControllerApi extends runtime.BaseAPI {

    /**
     * patch-hall-by-configurationhall-Id
     */
    async createPropertyReferenceConfigurationhallPatchRaw(requestParameters: CreatePropertyReferenceConfigurationhallPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceConfigurationhallPatch().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceConfigurationhallPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/configurationHalls/{id}/hall`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelHallFromJSON(jsonValue));
    }

    /**
     * patch-hall-by-configurationhall-Id
     */
    async createPropertyReferenceConfigurationhallPatch(requestParameters: CreatePropertyReferenceConfigurationhallPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelHall | null | undefined > {
        const response = await this.createPropertyReferenceConfigurationhallPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * update-hall-by-configurationhall-Id
     */
    async createPropertyReferenceConfigurationhallPutRaw(requestParameters: CreatePropertyReferenceConfigurationhallPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceConfigurationhallPut().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceConfigurationhallPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/configurationHalls/{id}/hall`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelHallFromJSON(jsonValue));
    }

    /**
     * update-hall-by-configurationhall-Id
     */
    async createPropertyReferenceConfigurationhallPut(requestParameters: CreatePropertyReferenceConfigurationhallPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelHall | null | undefined > {
        const response = await this.createPropertyReferenceConfigurationhallPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * delete-hall-by-configurationhall-Id
     */
    async deletePropertyReferenceConfigurationhallDeleteRaw(requestParameters: DeletePropertyReferenceConfigurationhallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceConfigurationhallDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/configurationHalls/{id}/hall`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-hall-by-configurationhall-Id
     */
    async deletePropertyReferenceConfigurationhallDelete(requestParameters: DeletePropertyReferenceConfigurationhallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceConfigurationhallDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * delete-hall-by-configurationhall-Id
     */
    async deletePropertyReferenceIdConfigurationhallDeleteRaw(requestParameters: DeletePropertyReferenceIdConfigurationhallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceIdConfigurationhallDelete().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling deletePropertyReferenceIdConfigurationhallDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/configurationHalls/{id}/hall/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-hall-by-configurationhall-Id
     */
    async deletePropertyReferenceIdConfigurationhallDelete(requestParameters: DeletePropertyReferenceIdConfigurationhallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceIdConfigurationhallDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-hall-by-configurationhall-Id
     */
    async followPropertyReferenceConfigurationhallGetRaw(requestParameters: FollowPropertyReferenceConfigurationhallGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceConfigurationhallGet().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling followPropertyReferenceConfigurationhallGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/configurationHalls/{id}/hall/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelHallFromJSON(jsonValue));
    }

    /**
     * get-hall-by-configurationhall-Id
     */
    async followPropertyReferenceConfigurationhallGet(requestParameters: FollowPropertyReferenceConfigurationhallGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelHall> {
        const response = await this.followPropertyReferenceConfigurationhallGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-hall-by-configurationhall-Id
     */
    async followPropertyReferenceConfigurationhallGet1Raw(requestParameters: FollowPropertyReferenceConfigurationhallGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceConfigurationhallGet1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/configurationHalls/{id}/hall`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelHallFromJSON(jsonValue));
    }

    /**
     * get-hall-by-configurationhall-Id
     */
    async followPropertyReferenceConfigurationhallGet1(requestParameters: FollowPropertyReferenceConfigurationhallGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelHall> {
        const response = await this.followPropertyReferenceConfigurationhallGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
