/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfigurationHallRequestBody,
  EntityModelConfigurationHall,
  PagedModelEntityModelConfigurationHall,
} from '../models/index';
import {
    ConfigurationHallRequestBodyFromJSON,
    ConfigurationHallRequestBodyToJSON,
    EntityModelConfigurationHallFromJSON,
    EntityModelConfigurationHallToJSON,
    PagedModelEntityModelConfigurationHallFromJSON,
    PagedModelEntityModelConfigurationHallToJSON,
} from '../models/index';

export interface DeleteItemResourceConfigurationhallDeleteRequest {
    id: string;
}

export interface GetCollectionResourceConfigurationhallGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceConfigurationhallGetRequest {
    id: string;
}

export interface PatchItemResourceConfigurationhallPatchRequest {
    id: string;
    configurationHallRequestBody: ConfigurationHallRequestBody;
}

export interface PostCollectionResourceConfigurationhallPostRequest {
    configurationHallRequestBody: ConfigurationHallRequestBody;
}

export interface PutItemResourceConfigurationhallPutRequest {
    id: string;
    configurationHallRequestBody: ConfigurationHallRequestBody;
}

/**
 * 
 */
export class ConfigurationHallEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-configurationhall
     */
    async deleteItemResourceConfigurationhallDeleteRaw(requestParameters: DeleteItemResourceConfigurationhallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceConfigurationhallDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/configurationHalls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-configurationhall
     */
    async deleteItemResourceConfigurationhallDelete(requestParameters: DeleteItemResourceConfigurationhallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceConfigurationhallDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-configurationhall
     */
    async getCollectionResourceConfigurationhallGet1Raw(requestParameters: GetCollectionResourceConfigurationhallGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelConfigurationHall>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/configurationHalls`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelConfigurationHallFromJSON(jsonValue));
    }

    /**
     * get-configurationhall
     */
    async getCollectionResourceConfigurationhallGet1(requestParameters: GetCollectionResourceConfigurationhallGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelConfigurationHall> {
        const response = await this.getCollectionResourceConfigurationhallGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-configurationhall
     */
    async getItemResourceConfigurationhallGetRaw(requestParameters: GetItemResourceConfigurationhallGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelConfigurationHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceConfigurationhallGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/configurationHalls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelConfigurationHallFromJSON(jsonValue));
    }

    /**
     * get-configurationhall
     */
    async getItemResourceConfigurationhallGet(requestParameters: GetItemResourceConfigurationhallGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelConfigurationHall> {
        const response = await this.getItemResourceConfigurationhallGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-configurationhall
     */
    async patchItemResourceConfigurationhallPatchRaw(requestParameters: PatchItemResourceConfigurationhallPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelConfigurationHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceConfigurationhallPatch().'
            );
        }

        if (requestParameters['configurationHallRequestBody'] == null) {
            throw new runtime.RequiredError(
                'configurationHallRequestBody',
                'Required parameter "configurationHallRequestBody" was null or undefined when calling patchItemResourceConfigurationhallPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/configurationHalls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigurationHallRequestBodyToJSON(requestParameters['configurationHallRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelConfigurationHallFromJSON(jsonValue));
    }

    /**
     * patch-configurationhall
     */
    async patchItemResourceConfigurationhallPatch(requestParameters: PatchItemResourceConfigurationhallPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelConfigurationHall | null | undefined > {
        const response = await this.patchItemResourceConfigurationhallPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-configurationhall
     */
    async postCollectionResourceConfigurationhallPostRaw(requestParameters: PostCollectionResourceConfigurationhallPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelConfigurationHall>> {
        if (requestParameters['configurationHallRequestBody'] == null) {
            throw new runtime.RequiredError(
                'configurationHallRequestBody',
                'Required parameter "configurationHallRequestBody" was null or undefined when calling postCollectionResourceConfigurationhallPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/configurationHalls`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigurationHallRequestBodyToJSON(requestParameters['configurationHallRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelConfigurationHallFromJSON(jsonValue));
    }

    /**
     * create-configurationhall
     */
    async postCollectionResourceConfigurationhallPost(requestParameters: PostCollectionResourceConfigurationhallPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelConfigurationHall> {
        const response = await this.postCollectionResourceConfigurationhallPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-configurationhall
     */
    async putItemResourceConfigurationhallPutRaw(requestParameters: PutItemResourceConfigurationhallPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelConfigurationHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceConfigurationhallPut().'
            );
        }

        if (requestParameters['configurationHallRequestBody'] == null) {
            throw new runtime.RequiredError(
                'configurationHallRequestBody',
                'Required parameter "configurationHallRequestBody" was null or undefined when calling putItemResourceConfigurationhallPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/configurationHalls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigurationHallRequestBodyToJSON(requestParameters['configurationHallRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelConfigurationHallFromJSON(jsonValue));
    }

    /**
     * update-configurationhall
     */
    async putItemResourceConfigurationhallPut(requestParameters: PutItemResourceConfigurationhallPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelConfigurationHall | null | undefined > {
        const response = await this.putItemResourceConfigurationhallPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
