/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomerDTO,
  GetVenueById404Response,
  GetVenueById422Response,
  GlobalErrorResponse,
} from '../models/index';
import {
    CustomerDTOFromJSON,
    CustomerDTOToJSON,
    GetVenueById404ResponseFromJSON,
    GetVenueById404ResponseToJSON,
    GetVenueById422ResponseFromJSON,
    GetVenueById422ResponseToJSON,
    GlobalErrorResponseFromJSON,
    GlobalErrorResponseToJSON,
} from '../models/index';

export interface CreateCustomerRequest {
    customerDTO: CustomerDTO;
}

export interface DeleteCustomerRequest {
    id: number;
}

export interface GetCustomerByEmailRequest {
    email: string;
}

export interface GetCustomerByIdRequest {
    id: number;
}

export interface GetCustomerByPhoneRequest {
    phoneNumber: string;
}

export interface GetCustomerByUsernameRequest {
    username: string;
}

export interface PatchCustomerRequest {
    id: number;
    customerDTO: CustomerDTO;
}

export interface UpdateCustomerRequest {
    id: number;
    customerDTO: CustomerDTO;
}

/**
 * 
 */
export class CustomerControllerApi extends runtime.BaseAPI {

    /**
     */
    async createCustomerRaw(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['customerDTO'] == null) {
            throw new runtime.RequiredError(
                'customerDTO',
                'Required parameter "customerDTO" was null or undefined when calling createCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/customers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerDTOToJSON(requestParameters['customerDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createCustomer(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createCustomerRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteCustomerRaw(requestParameters: DeleteCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/customers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteCustomer(requestParameters: DeleteCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCustomerRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllCustomersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CustomerDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/customers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CustomerDTOFromJSON));
    }

    /**
     */
    async getAllCustomers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CustomerDTO>> {
        const response = await this.getAllCustomersRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getCustomerByEmailRaw(requestParameters: GetCustomerByEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerDTO>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling getCustomerByEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/customers/email/{email}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerDTOFromJSON(jsonValue));
    }

    /**
     */
    async getCustomerByEmail(requestParameters: GetCustomerByEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerDTO> {
        const response = await this.getCustomerByEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCustomerByIdRaw(requestParameters: GetCustomerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCustomerById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/customers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerDTOFromJSON(jsonValue));
    }

    /**
     */
    async getCustomerById(requestParameters: GetCustomerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerDTO> {
        const response = await this.getCustomerByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCustomerByPhoneRaw(requestParameters: GetCustomerByPhoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerDTO>> {
        if (requestParameters['phoneNumber'] == null) {
            throw new runtime.RequiredError(
                'phoneNumber',
                'Required parameter "phoneNumber" was null or undefined when calling getCustomerByPhone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/customers/phoneNumber/{phoneNumber}`.replace(`{${"phoneNumber"}}`, encodeURIComponent(String(requestParameters['phoneNumber']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerDTOFromJSON(jsonValue));
    }

    /**
     */
    async getCustomerByPhone(requestParameters: GetCustomerByPhoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerDTO> {
        const response = await this.getCustomerByPhoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCustomerByUsernameRaw(requestParameters: GetCustomerByUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerDTO>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling getCustomerByUsername().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/customers/username/{username}`.replace(`{${"username"}}`, encodeURIComponent(String(requestParameters['username']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerDTOFromJSON(jsonValue));
    }

    /**
     */
    async getCustomerByUsername(requestParameters: GetCustomerByUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerDTO> {
        const response = await this.getCustomerByUsernameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async patchCustomerRaw(requestParameters: PatchCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchCustomer().'
            );
        }

        if (requestParameters['customerDTO'] == null) {
            throw new runtime.RequiredError(
                'customerDTO',
                'Required parameter "customerDTO" was null or undefined when calling patchCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/customers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerDTOToJSON(requestParameters['customerDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerDTOFromJSON(jsonValue));
    }

    /**
     */
    async patchCustomer(requestParameters: PatchCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerDTO> {
        const response = await this.patchCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateCustomerRaw(requestParameters: UpdateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCustomer().'
            );
        }

        if (requestParameters['customerDTO'] == null) {
            throw new runtime.RequiredError(
                'customerDTO',
                'Required parameter "customerDTO" was null or undefined when calling updateCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/customers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerDTOToJSON(requestParameters['customerDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateCustomer(requestParameters: UpdateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerDTO> {
        const response = await this.updateCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
