/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmployeeRequestBody,
  EntityModelEmployee,
  PagedModelEntityModelEmployee,
} from '../models/index';
import {
    EmployeeRequestBodyFromJSON,
    EmployeeRequestBodyToJSON,
    EntityModelEmployeeFromJSON,
    EntityModelEmployeeToJSON,
    PagedModelEntityModelEmployeeFromJSON,
    PagedModelEntityModelEmployeeToJSON,
} from '../models/index';

export interface DeleteItemResourceEmployeeDeleteRequest {
    id: string;
}

export interface GetCollectionResourceEmployeeGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceEmployeeGetRequest {
    id: string;
}

export interface PatchItemResourceEmployeePatchRequest {
    id: string;
    employeeRequestBody: EmployeeRequestBody;
}

export interface PostCollectionResourceEmployeePostRequest {
    employeeRequestBody: EmployeeRequestBody;
}

export interface PutItemResourceEmployeePutRequest {
    id: string;
    employeeRequestBody: EmployeeRequestBody;
}

/**
 * 
 */
export class EmployeeEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-employee
     */
    async deleteItemResourceEmployeeDeleteRaw(requestParameters: DeleteItemResourceEmployeeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceEmployeeDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/employees/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-employee
     */
    async deleteItemResourceEmployeeDelete(requestParameters: DeleteItemResourceEmployeeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceEmployeeDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-employee
     */
    async getCollectionResourceEmployeeGet1Raw(requestParameters: GetCollectionResourceEmployeeGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelEmployee>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/employees`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelEmployeeFromJSON(jsonValue));
    }

    /**
     * get-employee
     */
    async getCollectionResourceEmployeeGet1(requestParameters: GetCollectionResourceEmployeeGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelEmployee> {
        const response = await this.getCollectionResourceEmployeeGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-employee
     */
    async getItemResourceEmployeeGetRaw(requestParameters: GetItemResourceEmployeeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEmployee>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceEmployeeGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/employees/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEmployeeFromJSON(jsonValue));
    }

    /**
     * get-employee
     */
    async getItemResourceEmployeeGet(requestParameters: GetItemResourceEmployeeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEmployee> {
        const response = await this.getItemResourceEmployeeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-employee
     */
    async patchItemResourceEmployeePatchRaw(requestParameters: PatchItemResourceEmployeePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEmployee>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceEmployeePatch().'
            );
        }

        if (requestParameters['employeeRequestBody'] == null) {
            throw new runtime.RequiredError(
                'employeeRequestBody',
                'Required parameter "employeeRequestBody" was null or undefined when calling patchItemResourceEmployeePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/employees/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeRequestBodyToJSON(requestParameters['employeeRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEmployeeFromJSON(jsonValue));
    }

    /**
     * patch-employee
     */
    async patchItemResourceEmployeePatch(requestParameters: PatchItemResourceEmployeePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEmployee | null | undefined > {
        const response = await this.patchItemResourceEmployeePatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-employee
     */
    async postCollectionResourceEmployeePostRaw(requestParameters: PostCollectionResourceEmployeePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEmployee>> {
        if (requestParameters['employeeRequestBody'] == null) {
            throw new runtime.RequiredError(
                'employeeRequestBody',
                'Required parameter "employeeRequestBody" was null or undefined when calling postCollectionResourceEmployeePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/employees`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeRequestBodyToJSON(requestParameters['employeeRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEmployeeFromJSON(jsonValue));
    }

    /**
     * create-employee
     */
    async postCollectionResourceEmployeePost(requestParameters: PostCollectionResourceEmployeePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEmployee> {
        const response = await this.postCollectionResourceEmployeePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-employee
     */
    async putItemResourceEmployeePutRaw(requestParameters: PutItemResourceEmployeePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEmployee>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceEmployeePut().'
            );
        }

        if (requestParameters['employeeRequestBody'] == null) {
            throw new runtime.RequiredError(
                'employeeRequestBody',
                'Required parameter "employeeRequestBody" was null or undefined when calling putItemResourceEmployeePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/employees/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeRequestBodyToJSON(requestParameters['employeeRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEmployeeFromJSON(jsonValue));
    }

    /**
     * update-employee
     */
    async putItemResourceEmployeePut(requestParameters: PutItemResourceEmployeePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEmployee | null | undefined > {
        const response = await this.putItemResourceEmployeePutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
