/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmployeeDTO,
  EmployeeDTONoPwd,
  GetVenueById404Response,
  GetVenueById422Response,
  GlobalErrorResponse,
} from '../models/index';
import {
    EmployeeDTOFromJSON,
    EmployeeDTOToJSON,
    EmployeeDTONoPwdFromJSON,
    EmployeeDTONoPwdToJSON,
    GetVenueById404ResponseFromJSON,
    GetVenueById404ResponseToJSON,
    GetVenueById422ResponseFromJSON,
    GetVenueById422ResponseToJSON,
    GlobalErrorResponseFromJSON,
    GlobalErrorResponseToJSON,
} from '../models/index';

export interface CreateEmployeeRequest {
    employeeDTO: EmployeeDTO;
}

export interface DeleteEmployeeRequest {
    id: number;
}

export interface GetEmployeeByIdRequest {
    id: number;
}

export interface GetEmployeeByIdNoPwdRequest {
    id: number;
}

export interface PatchEmployeeRequest {
    id: number;
    requestBody: { [key: string]: object; };
}

export interface UpdateEmployeeRequest {
    id: number;
    employeeDTO: EmployeeDTO;
}

/**
 * 
 */
export class EmployeeControllerApi extends runtime.BaseAPI {

    /**
     */
    async createEmployeeRaw(requestParameters: CreateEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['employeeDTO'] == null) {
            throw new runtime.RequiredError(
                'employeeDTO',
                'Required parameter "employeeDTO" was null or undefined when calling createEmployee().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/employees`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeDTOToJSON(requestParameters['employeeDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createEmployee(requestParameters: CreateEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createEmployeeRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteEmployeeRaw(requestParameters: DeleteEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteEmployee().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/employees/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteEmployee(requestParameters: DeleteEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEmployeeRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllEmployeesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Set<EmployeeDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/employees`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => new Set(jsonValue.map(EmployeeDTOFromJSON)));
    }

    /**
     */
    async getAllEmployees(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Set<EmployeeDTO>> {
        const response = await this.getAllEmployeesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getEmployeeByIdRaw(requestParameters: GetEmployeeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmployeeById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/employees/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeDTOFromJSON(jsonValue));
    }

    /**
     */
    async getEmployeeById(requestParameters: GetEmployeeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeDTO> {
        const response = await this.getEmployeeByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getEmployeeByIdNoPwdRaw(requestParameters: GetEmployeeByIdNoPwdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeDTONoPwd>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmployeeByIdNoPwd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/employees/NoPwd/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeDTONoPwdFromJSON(jsonValue));
    }

    /**
     */
    async getEmployeeByIdNoPwd(requestParameters: GetEmployeeByIdNoPwdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeDTONoPwd> {
        const response = await this.getEmployeeByIdNoPwdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async patchEmployeeRaw(requestParameters: PatchEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchEmployee().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling patchEmployee().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/employees/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeDTOFromJSON(jsonValue));
    }

    /**
     */
    async patchEmployee(requestParameters: PatchEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeDTO> {
        const response = await this.patchEmployeeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateEmployeeRaw(requestParameters: UpdateEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEmployee().'
            );
        }

        if (requestParameters['employeeDTO'] == null) {
            throw new runtime.RequiredError(
                'employeeDTO',
                'Required parameter "employeeDTO" was null or undefined when calling updateEmployee().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/employees/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeDTOToJSON(requestParameters['employeeDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateEmployee(requestParameters: UpdateEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeDTO> {
        const response = await this.updateEmployeeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
