/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelEvent,
  EventRequestBody,
  PagedModelEntityModelEvent,
} from '../models/index';
import {
    EntityModelEventFromJSON,
    EntityModelEventToJSON,
    EventRequestBodyFromJSON,
    EventRequestBodyToJSON,
    PagedModelEntityModelEventFromJSON,
    PagedModelEntityModelEventToJSON,
} from '../models/index';

export interface DeleteItemResourceEventDeleteRequest {
    id: string;
}

export interface GetCollectionResourceEventGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceEventGetRequest {
    id: string;
}

export interface PatchItemResourceEventPatchRequest {
    id: string;
    eventRequestBody: EventRequestBody;
}

export interface PostCollectionResourceEventPostRequest {
    eventRequestBody: EventRequestBody;
}

export interface PutItemResourceEventPutRequest {
    id: string;
    eventRequestBody: EventRequestBody;
}

/**
 * 
 */
export class EventEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-event
     */
    async deleteItemResourceEventDeleteRaw(requestParameters: DeleteItemResourceEventDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceEventDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-event
     */
    async deleteItemResourceEventDelete(requestParameters: DeleteItemResourceEventDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceEventDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-event
     */
    async getCollectionResourceEventGet1Raw(requestParameters: GetCollectionResourceEventGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelEvent>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelEventFromJSON(jsonValue));
    }

    /**
     * get-event
     */
    async getCollectionResourceEventGet1(requestParameters: GetCollectionResourceEventGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelEvent> {
        const response = await this.getCollectionResourceEventGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-event
     */
    async getItemResourceEventGetRaw(requestParameters: GetItemResourceEventGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEvent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceEventGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEventFromJSON(jsonValue));
    }

    /**
     * get-event
     */
    async getItemResourceEventGet(requestParameters: GetItemResourceEventGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEvent> {
        const response = await this.getItemResourceEventGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-event
     */
    async patchItemResourceEventPatchRaw(requestParameters: PatchItemResourceEventPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEvent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceEventPatch().'
            );
        }

        if (requestParameters['eventRequestBody'] == null) {
            throw new runtime.RequiredError(
                'eventRequestBody',
                'Required parameter "eventRequestBody" was null or undefined when calling patchItemResourceEventPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EventRequestBodyToJSON(requestParameters['eventRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEventFromJSON(jsonValue));
    }

    /**
     * patch-event
     */
    async patchItemResourceEventPatch(requestParameters: PatchItemResourceEventPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEvent | null | undefined > {
        const response = await this.patchItemResourceEventPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-event
     */
    async postCollectionResourceEventPostRaw(requestParameters: PostCollectionResourceEventPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEvent>> {
        if (requestParameters['eventRequestBody'] == null) {
            throw new runtime.RequiredError(
                'eventRequestBody',
                'Required parameter "eventRequestBody" was null or undefined when calling postCollectionResourceEventPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventRequestBodyToJSON(requestParameters['eventRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEventFromJSON(jsonValue));
    }

    /**
     * create-event
     */
    async postCollectionResourceEventPost(requestParameters: PostCollectionResourceEventPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEvent> {
        const response = await this.postCollectionResourceEventPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-event
     */
    async putItemResourceEventPutRaw(requestParameters: PutItemResourceEventPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEvent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceEventPut().'
            );
        }

        if (requestParameters['eventRequestBody'] == null) {
            throw new runtime.RequiredError(
                'eventRequestBody',
                'Required parameter "eventRequestBody" was null or undefined when calling putItemResourceEventPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EventRequestBodyToJSON(requestParameters['eventRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEventFromJSON(jsonValue));
    }

    /**
     * update-event
     */
    async putItemResourceEventPut(requestParameters: PutItemResourceEventPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEvent | null | undefined > {
        const response = await this.putItemResourceEventPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
