/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelHall,
  HallRequestBody,
  PagedModelEntityModelHall,
} from '../models/index';
import {
    EntityModelHallFromJSON,
    EntityModelHallToJSON,
    HallRequestBodyFromJSON,
    HallRequestBodyToJSON,
    PagedModelEntityModelHallFromJSON,
    PagedModelEntityModelHallToJSON,
} from '../models/index';

export interface DeleteItemResourceHallDeleteRequest {
    id: string;
}

export interface GetCollectionResourceHallGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceHallGetRequest {
    id: string;
}

export interface PatchItemResourceHallPatchRequest {
    id: string;
    hallRequestBody: HallRequestBody;
}

export interface PostCollectionResourceHallPostRequest {
    hallRequestBody: HallRequestBody;
}

export interface PutItemResourceHallPutRequest {
    id: string;
    hallRequestBody: HallRequestBody;
}

/**
 * 
 */
export class HallEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-hall
     */
    async deleteItemResourceHallDeleteRaw(requestParameters: DeleteItemResourceHallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceHallDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/halls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-hall
     */
    async deleteItemResourceHallDelete(requestParameters: DeleteItemResourceHallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceHallDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-hall
     */
    async getCollectionResourceHallGet1Raw(requestParameters: GetCollectionResourceHallGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelHall>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/halls`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelHallFromJSON(jsonValue));
    }

    /**
     * get-hall
     */
    async getCollectionResourceHallGet1(requestParameters: GetCollectionResourceHallGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelHall> {
        const response = await this.getCollectionResourceHallGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-hall
     */
    async getItemResourceHallGetRaw(requestParameters: GetItemResourceHallGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceHallGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/halls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelHallFromJSON(jsonValue));
    }

    /**
     * get-hall
     */
    async getItemResourceHallGet(requestParameters: GetItemResourceHallGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelHall> {
        const response = await this.getItemResourceHallGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-hall
     */
    async patchItemResourceHallPatchRaw(requestParameters: PatchItemResourceHallPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceHallPatch().'
            );
        }

        if (requestParameters['hallRequestBody'] == null) {
            throw new runtime.RequiredError(
                'hallRequestBody',
                'Required parameter "hallRequestBody" was null or undefined when calling patchItemResourceHallPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/halls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: HallRequestBodyToJSON(requestParameters['hallRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelHallFromJSON(jsonValue));
    }

    /**
     * patch-hall
     */
    async patchItemResourceHallPatch(requestParameters: PatchItemResourceHallPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelHall | null | undefined > {
        const response = await this.patchItemResourceHallPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-hall
     */
    async postCollectionResourceHallPostRaw(requestParameters: PostCollectionResourceHallPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelHall>> {
        if (requestParameters['hallRequestBody'] == null) {
            throw new runtime.RequiredError(
                'hallRequestBody',
                'Required parameter "hallRequestBody" was null or undefined when calling postCollectionResourceHallPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/halls`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HallRequestBodyToJSON(requestParameters['hallRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelHallFromJSON(jsonValue));
    }

    /**
     * create-hall
     */
    async postCollectionResourceHallPost(requestParameters: PostCollectionResourceHallPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelHall> {
        const response = await this.postCollectionResourceHallPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-hall
     */
    async putItemResourceHallPutRaw(requestParameters: PutItemResourceHallPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceHallPut().'
            );
        }

        if (requestParameters['hallRequestBody'] == null) {
            throw new runtime.RequiredError(
                'hallRequestBody',
                'Required parameter "hallRequestBody" was null or undefined when calling putItemResourceHallPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/halls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: HallRequestBodyToJSON(requestParameters['hallRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelHallFromJSON(jsonValue));
    }

    /**
     * update-hall
     */
    async putItemResourceHallPut(requestParameters: PutItemResourceHallPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelHall | null | undefined > {
        const response = await this.putItemResourceHallPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
