/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionModelObject,
  EntityModelVenue,
} from '../models/index';
import {
    CollectionModelObjectFromJSON,
    CollectionModelObjectToJSON,
    EntityModelVenueFromJSON,
    EntityModelVenueToJSON,
} from '../models/index';

export interface CreatePropertyReferenceHallPatchRequest {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface CreatePropertyReferenceHallPutRequest {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface DeletePropertyReferenceHallDeleteRequest {
    id: string;
}

export interface DeletePropertyReferenceIdHallDeleteRequest {
    id: string;
    propertyId: string;
}

export interface FollowPropertyReferenceHallGetRequest {
    id: string;
    propertyId: string;
}

export interface FollowPropertyReferenceHallGet1Request {
    id: string;
}

/**
 * 
 */
export class HallPropertyReferenceControllerApi extends runtime.BaseAPI {

    /**
     * patch-venue-by-hall-Id
     */
    async createPropertyReferenceHallPatchRaw(requestParameters: CreatePropertyReferenceHallPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelVenue>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceHallPatch().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceHallPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/halls/{id}/venue`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelVenueFromJSON(jsonValue));
    }

    /**
     * patch-venue-by-hall-Id
     */
    async createPropertyReferenceHallPatch(requestParameters: CreatePropertyReferenceHallPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelVenue | null | undefined > {
        const response = await this.createPropertyReferenceHallPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * update-venue-by-hall-Id
     */
    async createPropertyReferenceHallPutRaw(requestParameters: CreatePropertyReferenceHallPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelVenue>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceHallPut().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceHallPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/halls/{id}/venue`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelVenueFromJSON(jsonValue));
    }

    /**
     * update-venue-by-hall-Id
     */
    async createPropertyReferenceHallPut(requestParameters: CreatePropertyReferenceHallPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelVenue | null | undefined > {
        const response = await this.createPropertyReferenceHallPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * delete-venue-by-hall-Id
     */
    async deletePropertyReferenceHallDeleteRaw(requestParameters: DeletePropertyReferenceHallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceHallDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/halls/{id}/venue`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-venue-by-hall-Id
     */
    async deletePropertyReferenceHallDelete(requestParameters: DeletePropertyReferenceHallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceHallDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * delete-venue-by-hall-Id
     */
    async deletePropertyReferenceIdHallDeleteRaw(requestParameters: DeletePropertyReferenceIdHallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceIdHallDelete().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling deletePropertyReferenceIdHallDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/halls/{id}/venue/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-venue-by-hall-Id
     */
    async deletePropertyReferenceIdHallDelete(requestParameters: DeletePropertyReferenceIdHallDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceIdHallDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-venue-by-hall-Id
     */
    async followPropertyReferenceHallGetRaw(requestParameters: FollowPropertyReferenceHallGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelVenue>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceHallGet().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling followPropertyReferenceHallGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/halls/{id}/venue/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelVenueFromJSON(jsonValue));
    }

    /**
     * get-venue-by-hall-Id
     */
    async followPropertyReferenceHallGet(requestParameters: FollowPropertyReferenceHallGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelVenue> {
        const response = await this.followPropertyReferenceHallGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-venue-by-hall-Id
     */
    async followPropertyReferenceHallGet1Raw(requestParameters: FollowPropertyReferenceHallGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelVenue>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceHallGet1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/halls/{id}/venue`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelVenueFromJSON(jsonValue));
    }

    /**
     * get-venue-by-hall-Id
     */
    async followPropertyReferenceHallGet1(requestParameters: FollowPropertyReferenceHallGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelVenue> {
        const response = await this.followPropertyReferenceHallGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
