/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetVenueById404Response,
  GetVenueById422Response,
  GlobalErrorResponse,
  HallDTO,
} from '../models/index';
import {
    GetVenueById404ResponseFromJSON,
    GetVenueById404ResponseToJSON,
    GetVenueById422ResponseFromJSON,
    GetVenueById422ResponseToJSON,
    GlobalErrorResponseFromJSON,
    GlobalErrorResponseToJSON,
    HallDTOFromJSON,
    HallDTOToJSON,
} from '../models/index';

export interface CreateHallForVenueIdRequest {
    venueId: number;
    hallDTO: HallDTO;
}

export interface DeleteHallRequest {
    id: number;
}

export interface GetHallByIdRequest {
    id: number;
}

export interface GetHallByVenueByIdRequest {
    venueId: number;
    id: number;
}

export interface GetHallsByVenueRequest {
    venueId: number;
}

export interface PatchHallRequest {
    id: number;
    requestBody: { [key: string]: object; };
}

export interface UpdateHallRequest {
    id: number;
    hallDTO: HallDTO;
}

/**
 * 
 */
export class HallControllerApi extends runtime.BaseAPI {

    /**
     */
    async createHallForVenueIdRaw(requestParameters: CreateHallForVenueIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling createHallForVenueId().'
            );
        }

        if (requestParameters['hallDTO'] == null) {
            throw new runtime.RequiredError(
                'hallDTO',
                'Required parameter "hallDTO" was null or undefined when calling createHallForVenueId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/venues/{venueId}/halls`.replace(`{${"venueId"}}`, encodeURIComponent(String(requestParameters['venueId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HallDTOToJSON(requestParameters['hallDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createHallForVenueId(requestParameters: CreateHallForVenueIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createHallForVenueIdRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteHallRaw(requestParameters: DeleteHallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteHall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/halls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteHall(requestParameters: DeleteHallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteHallRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllHallsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HallDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/halls`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HallDTOFromJSON));
    }

    /**
     */
    async getAllHalls(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HallDTO>> {
        const response = await this.getAllHallsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getHallByIdRaw(requestParameters: GetHallByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HallDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getHallById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/halls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HallDTOFromJSON(jsonValue));
    }

    /**
     */
    async getHallById(requestParameters: GetHallByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HallDTO> {
        const response = await this.getHallByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getHallByVenueByIdRaw(requestParameters: GetHallByVenueByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HallDTO>> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling getHallByVenueById().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getHallByVenueById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/venues/{venueId}/halls/{id}`.replace(`{${"venueId"}}`, encodeURIComponent(String(requestParameters['venueId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HallDTOFromJSON(jsonValue));
    }

    /**
     */
    async getHallByVenueById(requestParameters: GetHallByVenueByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HallDTO> {
        const response = await this.getHallByVenueByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getHallsByVenueRaw(requestParameters: GetHallsByVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HallDTO>>> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling getHallsByVenue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/venues/{venueId}/halls`.replace(`{${"venueId"}}`, encodeURIComponent(String(requestParameters['venueId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HallDTOFromJSON));
    }

    /**
     */
    async getHallsByVenue(requestParameters: GetHallsByVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HallDTO>> {
        const response = await this.getHallsByVenueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async patchHallRaw(requestParameters: PatchHallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HallDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchHall().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling patchHall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/halls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HallDTOFromJSON(jsonValue));
    }

    /**
     */
    async patchHall(requestParameters: PatchHallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HallDTO> {
        const response = await this.patchHallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateHallRaw(requestParameters: UpdateHallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HallDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateHall().'
            );
        }

        if (requestParameters['hallDTO'] == null) {
            throw new runtime.RequiredError(
                'hallDTO',
                'Required parameter "hallDTO" was null or undefined when calling updateHall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/halls/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: HallDTOToJSON(requestParameters['hallDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HallDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateHall(requestParameters: UpdateHallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HallDTO> {
        const response = await this.updateHallRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
