/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelPayment,
  PagedModelEntityModelPayment,
  PaymentRequestBody,
} from '../models/index';
import {
    EntityModelPaymentFromJSON,
    EntityModelPaymentToJSON,
    PagedModelEntityModelPaymentFromJSON,
    PagedModelEntityModelPaymentToJSON,
    PaymentRequestBodyFromJSON,
    PaymentRequestBodyToJSON,
} from '../models/index';

export interface DeleteItemResourcePaymentDeleteRequest {
    id: string;
}

export interface GetCollectionResourcePaymentGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourcePaymentGetRequest {
    id: string;
}

export interface PatchItemResourcePaymentPatchRequest {
    id: string;
    paymentRequestBody: PaymentRequestBody;
}

export interface PostCollectionResourcePaymentPostRequest {
    paymentRequestBody: PaymentRequestBody;
}

export interface PutItemResourcePaymentPutRequest {
    id: string;
    paymentRequestBody: PaymentRequestBody;
}

/**
 * 
 */
export class PaymentEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-payment
     */
    async deleteItemResourcePaymentDeleteRaw(requestParameters: DeleteItemResourcePaymentDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourcePaymentDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/payments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-payment
     */
    async deleteItemResourcePaymentDelete(requestParameters: DeleteItemResourcePaymentDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourcePaymentDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-payment
     */
    async getCollectionResourcePaymentGet1Raw(requestParameters: GetCollectionResourcePaymentGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelPayment>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/payments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelPaymentFromJSON(jsonValue));
    }

    /**
     * get-payment
     */
    async getCollectionResourcePaymentGet1(requestParameters: GetCollectionResourcePaymentGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelPayment> {
        const response = await this.getCollectionResourcePaymentGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-payment
     */
    async getItemResourcePaymentGetRaw(requestParameters: GetItemResourcePaymentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelPayment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourcePaymentGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/payments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelPaymentFromJSON(jsonValue));
    }

    /**
     * get-payment
     */
    async getItemResourcePaymentGet(requestParameters: GetItemResourcePaymentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelPayment> {
        const response = await this.getItemResourcePaymentGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-payment
     */
    async patchItemResourcePaymentPatchRaw(requestParameters: PatchItemResourcePaymentPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelPayment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourcePaymentPatch().'
            );
        }

        if (requestParameters['paymentRequestBody'] == null) {
            throw new runtime.RequiredError(
                'paymentRequestBody',
                'Required parameter "paymentRequestBody" was null or undefined when calling patchItemResourcePaymentPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/payments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentRequestBodyToJSON(requestParameters['paymentRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelPaymentFromJSON(jsonValue));
    }

    /**
     * patch-payment
     */
    async patchItemResourcePaymentPatch(requestParameters: PatchItemResourcePaymentPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelPayment | null | undefined > {
        const response = await this.patchItemResourcePaymentPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-payment
     */
    async postCollectionResourcePaymentPostRaw(requestParameters: PostCollectionResourcePaymentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelPayment>> {
        if (requestParameters['paymentRequestBody'] == null) {
            throw new runtime.RequiredError(
                'paymentRequestBody',
                'Required parameter "paymentRequestBody" was null or undefined when calling postCollectionResourcePaymentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/payments`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentRequestBodyToJSON(requestParameters['paymentRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelPaymentFromJSON(jsonValue));
    }

    /**
     * create-payment
     */
    async postCollectionResourcePaymentPost(requestParameters: PostCollectionResourcePaymentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelPayment> {
        const response = await this.postCollectionResourcePaymentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-payment
     */
    async putItemResourcePaymentPutRaw(requestParameters: PutItemResourcePaymentPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelPayment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourcePaymentPut().'
            );
        }

        if (requestParameters['paymentRequestBody'] == null) {
            throw new runtime.RequiredError(
                'paymentRequestBody',
                'Required parameter "paymentRequestBody" was null or undefined when calling putItemResourcePaymentPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/payments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentRequestBodyToJSON(requestParameters['paymentRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelPaymentFromJSON(jsonValue));
    }

    /**
     * update-payment
     */
    async putItemResourcePaymentPut(requestParameters: PutItemResourcePaymentPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelPayment | null | undefined > {
        const response = await this.putItemResourcePaymentPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
