/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelSeatStatus,
  PagedModelEntityModelSeatStatus,
  SeatStatusRequestBody,
} from '../models/index';
import {
    EntityModelSeatStatusFromJSON,
    EntityModelSeatStatusToJSON,
    PagedModelEntityModelSeatStatusFromJSON,
    PagedModelEntityModelSeatStatusToJSON,
    SeatStatusRequestBodyFromJSON,
    SeatStatusRequestBodyToJSON,
} from '../models/index';

export interface DeleteItemResourceSeatstatusDeleteRequest {
    id: string;
}

export interface GetCollectionResourceSeatstatusGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceSeatstatusGetRequest {
    id: string;
}

export interface PatchItemResourceSeatstatusPatchRequest {
    id: string;
    seatStatusRequestBody: SeatStatusRequestBody;
}

export interface PostCollectionResourceSeatstatusPostRequest {
    seatStatusRequestBody: SeatStatusRequestBody;
}

export interface PutItemResourceSeatstatusPutRequest {
    id: string;
    seatStatusRequestBody: SeatStatusRequestBody;
}

/**
 * 
 */
export class SeatStatusEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-seatstatus
     */
    async deleteItemResourceSeatstatusDeleteRaw(requestParameters: DeleteItemResourceSeatstatusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceSeatstatusDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/seatStatuses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-seatstatus
     */
    async deleteItemResourceSeatstatusDelete(requestParameters: DeleteItemResourceSeatstatusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceSeatstatusDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-seatstatus
     */
    async getCollectionResourceSeatstatusGet1Raw(requestParameters: GetCollectionResourceSeatstatusGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelSeatStatus>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/seatStatuses`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelSeatStatusFromJSON(jsonValue));
    }

    /**
     * get-seatstatus
     */
    async getCollectionResourceSeatstatusGet1(requestParameters: GetCollectionResourceSeatstatusGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelSeatStatus> {
        const response = await this.getCollectionResourceSeatstatusGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-seatstatus
     */
    async getItemResourceSeatstatusGetRaw(requestParameters: GetItemResourceSeatstatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelSeatStatus>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceSeatstatusGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/seatStatuses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelSeatStatusFromJSON(jsonValue));
    }

    /**
     * get-seatstatus
     */
    async getItemResourceSeatstatusGet(requestParameters: GetItemResourceSeatstatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelSeatStatus> {
        const response = await this.getItemResourceSeatstatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-seatstatus
     */
    async patchItemResourceSeatstatusPatchRaw(requestParameters: PatchItemResourceSeatstatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelSeatStatus>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceSeatstatusPatch().'
            );
        }

        if (requestParameters['seatStatusRequestBody'] == null) {
            throw new runtime.RequiredError(
                'seatStatusRequestBody',
                'Required parameter "seatStatusRequestBody" was null or undefined when calling patchItemResourceSeatstatusPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/seatStatuses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SeatStatusRequestBodyToJSON(requestParameters['seatStatusRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelSeatStatusFromJSON(jsonValue));
    }

    /**
     * patch-seatstatus
     */
    async patchItemResourceSeatstatusPatch(requestParameters: PatchItemResourceSeatstatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelSeatStatus | null | undefined > {
        const response = await this.patchItemResourceSeatstatusPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-seatstatus
     */
    async postCollectionResourceSeatstatusPostRaw(requestParameters: PostCollectionResourceSeatstatusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelSeatStatus>> {
        if (requestParameters['seatStatusRequestBody'] == null) {
            throw new runtime.RequiredError(
                'seatStatusRequestBody',
                'Required parameter "seatStatusRequestBody" was null or undefined when calling postCollectionResourceSeatstatusPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/seatStatuses`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SeatStatusRequestBodyToJSON(requestParameters['seatStatusRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelSeatStatusFromJSON(jsonValue));
    }

    /**
     * create-seatstatus
     */
    async postCollectionResourceSeatstatusPost(requestParameters: PostCollectionResourceSeatstatusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelSeatStatus> {
        const response = await this.postCollectionResourceSeatstatusPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-seatstatus
     */
    async putItemResourceSeatstatusPutRaw(requestParameters: PutItemResourceSeatstatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelSeatStatus>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceSeatstatusPut().'
            );
        }

        if (requestParameters['seatStatusRequestBody'] == null) {
            throw new runtime.RequiredError(
                'seatStatusRequestBody',
                'Required parameter "seatStatusRequestBody" was null or undefined when calling putItemResourceSeatstatusPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/seatStatuses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SeatStatusRequestBodyToJSON(requestParameters['seatStatusRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelSeatStatusFromJSON(jsonValue));
    }

    /**
     * update-seatstatus
     */
    async putItemResourceSeatstatusPut(requestParameters: PutItemResourceSeatstatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelSeatStatus | null | undefined > {
        const response = await this.putItemResourceSeatstatusPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
