/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionModelEntityModelSeat,
} from '../models/index';
import {
    CollectionModelEntityModelSeatFromJSON,
    CollectionModelEntityModelSeatToJSON,
} from '../models/index';

export interface ExecuteSearchSeatGetRequest {
    configurationHallId?: number;
}

/**
 * 
 */
export class SeatSearchControllerApi extends runtime.BaseAPI {

    /**
     */
    async executeSearchSeatGetRaw(requestParameters: ExecuteSearchSeatGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelEntityModelSeat>> {
        const queryParameters: any = {};

        if (requestParameters['configurationHallId'] != null) {
            queryParameters['configurationHallId'] = requestParameters['configurationHallId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/seats/search/findByConfigurationHallId`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelEntityModelSeatFromJSON(jsonValue));
    }

    /**
     */
    async executeSearchSeatGet(requestParameters: ExecuteSearchSeatGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelEntityModelSeat> {
        const response = await this.executeSearchSeatGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
