/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelSeatStatus,
} from '../models/index';
import {
    EntityModelSeatStatusFromJSON,
    EntityModelSeatStatusToJSON,
} from '../models/index';

export interface ExecuteSearchSeatstatusGetRequest {
    name?: string;
}

/**
 * 
 */
export class SeatStatusSearchControllerApi extends runtime.BaseAPI {

    /**
     */
    async executeSearchSeatstatusGetRaw(requestParameters: ExecuteSearchSeatstatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelSeatStatus>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/seatStatuses/search/findByName`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelSeatStatusFromJSON(jsonValue));
    }

    /**
     */
    async executeSearchSeatstatusGet(requestParameters: ExecuteSearchSeatstatusGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelSeatStatus> {
        const response = await this.executeSearchSeatstatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
