/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelSeat,
  PagedModelEntityModelSeat,
  SeatRequestBody,
} from '../models/index';
import {
    EntityModelSeatFromJSON,
    EntityModelSeatToJSON,
    PagedModelEntityModelSeatFromJSON,
    PagedModelEntityModelSeatToJSON,
    SeatRequestBodyFromJSON,
    SeatRequestBodyToJSON,
} from '../models/index';

export interface DeleteItemResourceSeatDeleteRequest {
    id: string;
}

export interface GetCollectionResourceSeatGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceSeatGetRequest {
    id: string;
}

export interface PatchItemResourceSeatPatchRequest {
    id: string;
    seatRequestBody: SeatRequestBody;
}

export interface PostCollectionResourceSeatPostRequest {
    seatRequestBody: SeatRequestBody;
}

export interface PutItemResourceSeatPutRequest {
    id: string;
    seatRequestBody: SeatRequestBody;
}

/**
 * 
 */
export class SeatEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-seat
     */
    async deleteItemResourceSeatDeleteRaw(requestParameters: DeleteItemResourceSeatDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceSeatDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/seats/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-seat
     */
    async deleteItemResourceSeatDelete(requestParameters: DeleteItemResourceSeatDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceSeatDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-seat
     */
    async getCollectionResourceSeatGet1Raw(requestParameters: GetCollectionResourceSeatGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelSeat>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/seats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelSeatFromJSON(jsonValue));
    }

    /**
     * get-seat
     */
    async getCollectionResourceSeatGet1(requestParameters: GetCollectionResourceSeatGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelSeat> {
        const response = await this.getCollectionResourceSeatGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-seat
     */
    async getItemResourceSeatGetRaw(requestParameters: GetItemResourceSeatGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelSeat>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceSeatGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/seats/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelSeatFromJSON(jsonValue));
    }

    /**
     * get-seat
     */
    async getItemResourceSeatGet(requestParameters: GetItemResourceSeatGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelSeat> {
        const response = await this.getItemResourceSeatGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-seat
     */
    async patchItemResourceSeatPatchRaw(requestParameters: PatchItemResourceSeatPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelSeat>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceSeatPatch().'
            );
        }

        if (requestParameters['seatRequestBody'] == null) {
            throw new runtime.RequiredError(
                'seatRequestBody',
                'Required parameter "seatRequestBody" was null or undefined when calling patchItemResourceSeatPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/seats/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SeatRequestBodyToJSON(requestParameters['seatRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelSeatFromJSON(jsonValue));
    }

    /**
     * patch-seat
     */
    async patchItemResourceSeatPatch(requestParameters: PatchItemResourceSeatPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelSeat | null | undefined > {
        const response = await this.patchItemResourceSeatPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-seat
     */
    async postCollectionResourceSeatPostRaw(requestParameters: PostCollectionResourceSeatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelSeat>> {
        if (requestParameters['seatRequestBody'] == null) {
            throw new runtime.RequiredError(
                'seatRequestBody',
                'Required parameter "seatRequestBody" was null or undefined when calling postCollectionResourceSeatPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/seats`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SeatRequestBodyToJSON(requestParameters['seatRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelSeatFromJSON(jsonValue));
    }

    /**
     * create-seat
     */
    async postCollectionResourceSeatPost(requestParameters: PostCollectionResourceSeatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelSeat> {
        const response = await this.postCollectionResourceSeatPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-seat
     */
    async putItemResourceSeatPutRaw(requestParameters: PutItemResourceSeatPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelSeat>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceSeatPut().'
            );
        }

        if (requestParameters['seatRequestBody'] == null) {
            throw new runtime.RequiredError(
                'seatRequestBody',
                'Required parameter "seatRequestBody" was null or undefined when calling putItemResourceSeatPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/seats/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SeatRequestBodyToJSON(requestParameters['seatRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelSeatFromJSON(jsonValue));
    }

    /**
     * update-seat
     */
    async putItemResourceSeatPut(requestParameters: PutItemResourceSeatPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelSeat | null | undefined > {
        const response = await this.putItemResourceSeatPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
