/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetVenueById404Response,
  GetVenueById422Response,
  GlobalErrorResponse,
  SessionEventDTO,
} from '../models/index';
import {
    GetVenueById404ResponseFromJSON,
    GetVenueById404ResponseToJSON,
    GetVenueById422ResponseFromJSON,
    GetVenueById422ResponseToJSON,
    GlobalErrorResponseFromJSON,
    GlobalErrorResponseToJSON,
    SessionEventDTOFromJSON,
    SessionEventDTOToJSON,
} from '../models/index';

export interface GetSessionEventByIdRequest {
    sessionEventId: number;
}

/**
 * 
 */
export class SessionEventControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllSessionEventsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SessionEventDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/sessionevents`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SessionEventDTOFromJSON));
    }

    /**
     */
    async getAllSessionEvents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SessionEventDTO>> {
        const response = await this.getAllSessionEventsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getSessionEventByIdRaw(requestParameters: GetSessionEventByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionEventDTO>> {
        if (requestParameters['sessionEventId'] == null) {
            throw new runtime.RequiredError(
                'sessionEventId',
                'Required parameter "sessionEventId" was null or undefined when calling getSessionEventById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/sessionevents/{sessionEventId}`.replace(`{${"sessionEventId"}}`, encodeURIComponent(String(requestParameters['sessionEventId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionEventDTOFromJSON(jsonValue));
    }

    /**
     */
    async getSessionEventById(requestParameters: GetSessionEventByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionEventDTO> {
        const response = await this.getSessionEventByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
