/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionModelObject,
  EntityModelConfigurationHall,
  EntityModelEvent,
} from '../models/index';
import {
    CollectionModelObjectFromJSON,
    CollectionModelObjectToJSON,
    EntityModelConfigurationHallFromJSON,
    EntityModelConfigurationHallToJSON,
    EntityModelEventFromJSON,
    EntityModelEventToJSON,
} from '../models/index';

export interface CreatePropertyReferenceSessioneventPatchRequest {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface CreatePropertyReferenceSessioneventPatch1Request {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface CreatePropertyReferenceSessioneventPutRequest {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface CreatePropertyReferenceSessioneventPut1Request {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface DeletePropertyReferenceIdSessioneventDeleteRequest {
    id: string;
    propertyId: string;
}

export interface DeletePropertyReferenceIdSessioneventDelete1Request {
    id: string;
    propertyId: string;
}

export interface DeletePropertyReferenceSessioneventDeleteRequest {
    id: string;
}

export interface DeletePropertyReferenceSessioneventDelete1Request {
    id: string;
}

export interface FollowPropertyReferenceSessioneventGetRequest {
    id: string;
    propertyId: string;
}

export interface FollowPropertyReferenceSessioneventGet1Request {
    id: string;
}

export interface FollowPropertyReferenceSessioneventGet2Request {
    id: string;
    propertyId: string;
}

export interface FollowPropertyReferenceSessioneventGet21Request {
    id: string;
}

/**
 * 
 */
export class SessionEventPropertyReferenceControllerApi extends runtime.BaseAPI {

    /**
     * patch-configurationhall-by-sessionevent-Id
     */
    async createPropertyReferenceSessioneventPatchRaw(requestParameters: CreatePropertyReferenceSessioneventPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelConfigurationHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceSessioneventPatch().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceSessioneventPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/sessionEvents/{id}/configurationHall`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelConfigurationHallFromJSON(jsonValue));
    }

    /**
     * patch-configurationhall-by-sessionevent-Id
     */
    async createPropertyReferenceSessioneventPatch(requestParameters: CreatePropertyReferenceSessioneventPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelConfigurationHall | null | undefined > {
        const response = await this.createPropertyReferenceSessioneventPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * patch-event-by-sessionevent-Id
     */
    async createPropertyReferenceSessioneventPatch1Raw(requestParameters: CreatePropertyReferenceSessioneventPatch1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEvent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceSessioneventPatch1().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceSessioneventPatch1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/sessionEvents/{id}/event`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEventFromJSON(jsonValue));
    }

    /**
     * patch-event-by-sessionevent-Id
     */
    async createPropertyReferenceSessioneventPatch1(requestParameters: CreatePropertyReferenceSessioneventPatch1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEvent | null | undefined > {
        const response = await this.createPropertyReferenceSessioneventPatch1Raw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * update-configurationhall-by-sessionevent-Id
     */
    async createPropertyReferenceSessioneventPutRaw(requestParameters: CreatePropertyReferenceSessioneventPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelConfigurationHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceSessioneventPut().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceSessioneventPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/sessionEvents/{id}/configurationHall`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelConfigurationHallFromJSON(jsonValue));
    }

    /**
     * update-configurationhall-by-sessionevent-Id
     */
    async createPropertyReferenceSessioneventPut(requestParameters: CreatePropertyReferenceSessioneventPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelConfigurationHall | null | undefined > {
        const response = await this.createPropertyReferenceSessioneventPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * update-event-by-sessionevent-Id
     */
    async createPropertyReferenceSessioneventPut1Raw(requestParameters: CreatePropertyReferenceSessioneventPut1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEvent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceSessioneventPut1().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceSessioneventPut1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/sessionEvents/{id}/event`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEventFromJSON(jsonValue));
    }

    /**
     * update-event-by-sessionevent-Id
     */
    async createPropertyReferenceSessioneventPut1(requestParameters: CreatePropertyReferenceSessioneventPut1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEvent | null | undefined > {
        const response = await this.createPropertyReferenceSessioneventPut1Raw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * delete-configurationhall-by-sessionevent-Id
     */
    async deletePropertyReferenceIdSessioneventDeleteRaw(requestParameters: DeletePropertyReferenceIdSessioneventDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceIdSessioneventDelete().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling deletePropertyReferenceIdSessioneventDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessionEvents/{id}/configurationHall/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-configurationhall-by-sessionevent-Id
     */
    async deletePropertyReferenceIdSessioneventDelete(requestParameters: DeletePropertyReferenceIdSessioneventDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceIdSessioneventDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * delete-event-by-sessionevent-Id
     */
    async deletePropertyReferenceIdSessioneventDelete1Raw(requestParameters: DeletePropertyReferenceIdSessioneventDelete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceIdSessioneventDelete1().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling deletePropertyReferenceIdSessioneventDelete1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessionEvents/{id}/event/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-event-by-sessionevent-Id
     */
    async deletePropertyReferenceIdSessioneventDelete1(requestParameters: DeletePropertyReferenceIdSessioneventDelete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceIdSessioneventDelete1Raw(requestParameters, initOverrides);
    }

    /**
     * delete-configurationhall-by-sessionevent-Id
     */
    async deletePropertyReferenceSessioneventDeleteRaw(requestParameters: DeletePropertyReferenceSessioneventDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceSessioneventDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessionEvents/{id}/configurationHall`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-configurationhall-by-sessionevent-Id
     */
    async deletePropertyReferenceSessioneventDelete(requestParameters: DeletePropertyReferenceSessioneventDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceSessioneventDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * delete-event-by-sessionevent-Id
     */
    async deletePropertyReferenceSessioneventDelete1Raw(requestParameters: DeletePropertyReferenceSessioneventDelete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceSessioneventDelete1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessionEvents/{id}/event`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-event-by-sessionevent-Id
     */
    async deletePropertyReferenceSessioneventDelete1(requestParameters: DeletePropertyReferenceSessioneventDelete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceSessioneventDelete1Raw(requestParameters, initOverrides);
    }

    /**
     * get-configurationhall-by-sessionevent-Id
     */
    async followPropertyReferenceSessioneventGetRaw(requestParameters: FollowPropertyReferenceSessioneventGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelConfigurationHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceSessioneventGet().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling followPropertyReferenceSessioneventGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessionEvents/{id}/configurationHall/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelConfigurationHallFromJSON(jsonValue));
    }

    /**
     * get-configurationhall-by-sessionevent-Id
     */
    async followPropertyReferenceSessioneventGet(requestParameters: FollowPropertyReferenceSessioneventGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelConfigurationHall> {
        const response = await this.followPropertyReferenceSessioneventGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-configurationhall-by-sessionevent-Id
     */
    async followPropertyReferenceSessioneventGet1Raw(requestParameters: FollowPropertyReferenceSessioneventGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelConfigurationHall>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceSessioneventGet1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessionEvents/{id}/configurationHall`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelConfigurationHallFromJSON(jsonValue));
    }

    /**
     * get-configurationhall-by-sessionevent-Id
     */
    async followPropertyReferenceSessioneventGet1(requestParameters: FollowPropertyReferenceSessioneventGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelConfigurationHall> {
        const response = await this.followPropertyReferenceSessioneventGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-event-by-sessionevent-Id
     */
    async followPropertyReferenceSessioneventGet2Raw(requestParameters: FollowPropertyReferenceSessioneventGet2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEvent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceSessioneventGet2().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling followPropertyReferenceSessioneventGet2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessionEvents/{id}/event/{propertyId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEventFromJSON(jsonValue));
    }

    /**
     * get-event-by-sessionevent-Id
     */
    async followPropertyReferenceSessioneventGet2(requestParameters: FollowPropertyReferenceSessioneventGet2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEvent> {
        const response = await this.followPropertyReferenceSessioneventGet2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-event-by-sessionevent-Id
     */
    async followPropertyReferenceSessioneventGet21Raw(requestParameters: FollowPropertyReferenceSessioneventGet21Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelEvent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceSessioneventGet21().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessionEvents/{id}/event`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelEventFromJSON(jsonValue));
    }

    /**
     * get-event-by-sessionevent-Id
     */
    async followPropertyReferenceSessioneventGet21(requestParameters: FollowPropertyReferenceSessioneventGet21Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelEvent> {
        const response = await this.followPropertyReferenceSessioneventGet21Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
