/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionModelEntityModelSessionEvent,
} from '../models/index';
import {
    CollectionModelEntityModelSessionEventFromJSON,
    CollectionModelEntityModelSessionEventToJSON,
} from '../models/index';

export interface ExecuteSearchSessioneventGetRequest {
    eventId?: number;
}

/**
 * 
 */
export class SessionEventSearchControllerApi extends runtime.BaseAPI {

    /**
     */
    async executeSearchSessioneventGetRaw(requestParameters: ExecuteSearchSessioneventGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelEntityModelSessionEvent>> {
        const queryParameters: any = {};

        if (requestParameters['eventId'] != null) {
            queryParameters['eventId'] = requestParameters['eventId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessionEvents/search/findAllByEventId`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelEntityModelSessionEventFromJSON(jsonValue));
    }

    /**
     */
    async executeSearchSessioneventGet(requestParameters: ExecuteSearchSessioneventGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelEntityModelSessionEvent> {
        const response = await this.executeSearchSessioneventGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
