/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetVenueById404Response,
  GetVenueById422Response,
  GlobalErrorResponse,
  TicketReservationDTO,
} from '../models/index';
import {
    GetVenueById404ResponseFromJSON,
    GetVenueById404ResponseToJSON,
    GetVenueById422ResponseFromJSON,
    GetVenueById422ResponseToJSON,
    GlobalErrorResponseFromJSON,
    GlobalErrorResponseToJSON,
    TicketReservationDTOFromJSON,
    TicketReservationDTOToJSON,
} from '../models/index';

export interface CreateTicketReservationRequest {
    ticketReservationDTO: TicketReservationDTO;
}

export interface GetTicketReservationByIdRequest {
    seatId: number;
    sessioneventId: number;
}

/**
 * 
 */
export class TicketReservationControllerApi extends runtime.BaseAPI {

    /**
     */
    async createTicketReservationRaw(requestParameters: CreateTicketReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['ticketReservationDTO'] == null) {
            throw new runtime.RequiredError(
                'ticketReservationDTO',
                'Required parameter "ticketReservationDTO" was null or undefined when calling createTicketReservation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/ticketReservations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TicketReservationDTOToJSON(requestParameters['ticketReservationDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createTicketReservation(requestParameters: CreateTicketReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createTicketReservationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllTicketReservationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Set<TicketReservationDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/ticketReservations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => new Set(jsonValue.map(TicketReservationDTOFromJSON)));
    }

    /**
     */
    async getAllTicketReservations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Set<TicketReservationDTO>> {
        const response = await this.getAllTicketReservationsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getTicketReservationByIdRaw(requestParameters: GetTicketReservationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketReservationDTO>> {
        if (requestParameters['seatId'] == null) {
            throw new runtime.RequiredError(
                'seatId',
                'Required parameter "seatId" was null or undefined when calling getTicketReservationById().'
            );
        }

        if (requestParameters['sessioneventId'] == null) {
            throw new runtime.RequiredError(
                'sessioneventId',
                'Required parameter "sessioneventId" was null or undefined when calling getTicketReservationById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/ticketReservations/sessionevent/{sessioneventId}/seat/{seatId}`.replace(`{${"seatId"}}`, encodeURIComponent(String(requestParameters['seatId']))).replace(`{${"sessioneventId"}}`, encodeURIComponent(String(requestParameters['sessioneventId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketReservationDTOFromJSON(jsonValue));
    }

    /**
     */
    async getTicketReservationById(requestParameters: GetTicketReservationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketReservationDTO> {
        const response = await this.getTicketReservationByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
