/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelTicketReservation,
  PagedModelEntityModelTicketReservation,
  TicketReservationRequestBody,
} from '../models/index';
import {
    EntityModelTicketReservationFromJSON,
    EntityModelTicketReservationToJSON,
    PagedModelEntityModelTicketReservationFromJSON,
    PagedModelEntityModelTicketReservationToJSON,
    TicketReservationRequestBodyFromJSON,
    TicketReservationRequestBodyToJSON,
} from '../models/index';

export interface DeleteItemResourceTicketreservationDeleteRequest {
    id: string;
}

export interface GetCollectionResourceTicketreservationGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceTicketreservationGetRequest {
    id: string;
}

export interface PatchItemResourceTicketreservationPatchRequest {
    id: string;
    ticketReservationRequestBody: TicketReservationRequestBody;
}

export interface PostCollectionResourceTicketreservationPostRequest {
    ticketReservationRequestBody: TicketReservationRequestBody;
}

export interface PutItemResourceTicketreservationPutRequest {
    id: string;
    ticketReservationRequestBody: TicketReservationRequestBody;
}

/**
 * 
 */
export class TicketReservationEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-ticketreservation
     */
    async deleteItemResourceTicketreservationDeleteRaw(requestParameters: DeleteItemResourceTicketreservationDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceTicketreservationDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ticketReservations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-ticketreservation
     */
    async deleteItemResourceTicketreservationDelete(requestParameters: DeleteItemResourceTicketreservationDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceTicketreservationDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-ticketreservation
     */
    async getCollectionResourceTicketreservationGet1Raw(requestParameters: GetCollectionResourceTicketreservationGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelTicketReservation>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ticketReservations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelTicketReservationFromJSON(jsonValue));
    }

    /**
     * get-ticketreservation
     */
    async getCollectionResourceTicketreservationGet1(requestParameters: GetCollectionResourceTicketreservationGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelTicketReservation> {
        const response = await this.getCollectionResourceTicketreservationGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-ticketreservation
     */
    async getItemResourceTicketreservationGetRaw(requestParameters: GetItemResourceTicketreservationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelTicketReservation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceTicketreservationGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ticketReservations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelTicketReservationFromJSON(jsonValue));
    }

    /**
     * get-ticketreservation
     */
    async getItemResourceTicketreservationGet(requestParameters: GetItemResourceTicketreservationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelTicketReservation> {
        const response = await this.getItemResourceTicketreservationGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-ticketreservation
     */
    async patchItemResourceTicketreservationPatchRaw(requestParameters: PatchItemResourceTicketreservationPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelTicketReservation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceTicketreservationPatch().'
            );
        }

        if (requestParameters['ticketReservationRequestBody'] == null) {
            throw new runtime.RequiredError(
                'ticketReservationRequestBody',
                'Required parameter "ticketReservationRequestBody" was null or undefined when calling patchItemResourceTicketreservationPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/ticketReservations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TicketReservationRequestBodyToJSON(requestParameters['ticketReservationRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelTicketReservationFromJSON(jsonValue));
    }

    /**
     * patch-ticketreservation
     */
    async patchItemResourceTicketreservationPatch(requestParameters: PatchItemResourceTicketreservationPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelTicketReservation | null | undefined > {
        const response = await this.patchItemResourceTicketreservationPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-ticketreservation
     */
    async postCollectionResourceTicketreservationPostRaw(requestParameters: PostCollectionResourceTicketreservationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelTicketReservation>> {
        if (requestParameters['ticketReservationRequestBody'] == null) {
            throw new runtime.RequiredError(
                'ticketReservationRequestBody',
                'Required parameter "ticketReservationRequestBody" was null or undefined when calling postCollectionResourceTicketreservationPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/ticketReservations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TicketReservationRequestBodyToJSON(requestParameters['ticketReservationRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelTicketReservationFromJSON(jsonValue));
    }

    /**
     * create-ticketreservation
     */
    async postCollectionResourceTicketreservationPost(requestParameters: PostCollectionResourceTicketreservationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelTicketReservation> {
        const response = await this.postCollectionResourceTicketreservationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-ticketreservation
     */
    async putItemResourceTicketreservationPutRaw(requestParameters: PutItemResourceTicketreservationPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelTicketReservation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceTicketreservationPut().'
            );
        }

        if (requestParameters['ticketReservationRequestBody'] == null) {
            throw new runtime.RequiredError(
                'ticketReservationRequestBody',
                'Required parameter "ticketReservationRequestBody" was null or undefined when calling putItemResourceTicketreservationPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/ticketReservations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TicketReservationRequestBodyToJSON(requestParameters['ticketReservationRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelTicketReservationFromJSON(jsonValue));
    }

    /**
     * update-ticketreservation
     */
    async putItemResourceTicketreservationPut(requestParameters: PutItemResourceTicketreservationPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelTicketReservation | null | undefined > {
        const response = await this.putItemResourceTicketreservationPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
