/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionModelEntityModelVenue,
  EntityModelVenue,
} from '../models/index';
import {
    CollectionModelEntityModelVenueFromJSON,
    CollectionModelEntityModelVenueToJSON,
    EntityModelVenueFromJSON,
    EntityModelVenueToJSON,
} from '../models/index';

export interface ExecuteSearchVenueGetRequest {
    id?: number;
}

export interface ExecuteSearchVenueGet1Request {
    name?: string;
}

export interface ExecuteSearchVenueGet2Request {
    id?: number;
}

/**
 * 
 */
export class VenueSearchControllerApi extends runtime.BaseAPI {

    /**
     */
    async executeSearchVenueGetRaw(requestParameters: ExecuteSearchVenueGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelEntityModelVenue>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/venues/search/findAllEmployeesById`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelEntityModelVenueFromJSON(jsonValue));
    }

    /**
     */
    async executeSearchVenueGet(requestParameters: ExecuteSearchVenueGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelEntityModelVenue> {
        const response = await this.executeSearchVenueGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async executeSearchVenueGet1Raw(requestParameters: ExecuteSearchVenueGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelVenue>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/venues/search/findByName`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelVenueFromJSON(jsonValue));
    }

    /**
     */
    async executeSearchVenueGet1(requestParameters: ExecuteSearchVenueGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelVenue> {
        const response = await this.executeSearchVenueGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async executeSearchVenueGet2Raw(requestParameters: ExecuteSearchVenueGet2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelVenue>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/venues/search/findEmployeeById`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelVenueFromJSON(jsonValue));
    }

    /**
     */
    async executeSearchVenueGet2(requestParameters: ExecuteSearchVenueGet2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelVenue> {
        const response = await this.executeSearchVenueGet2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
