/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelVenue,
  PagedModelEntityModelVenue,
  VenueRequestBody,
} from '../models/index';
import {
    EntityModelVenueFromJSON,
    EntityModelVenueToJSON,
    PagedModelEntityModelVenueFromJSON,
    PagedModelEntityModelVenueToJSON,
    VenueRequestBodyFromJSON,
    VenueRequestBodyToJSON,
} from '../models/index';

export interface DeleteItemResourceVenueDeleteRequest {
    id: string;
}

export interface GetCollectionResourceVenueGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceVenueGetRequest {
    id: string;
}

export interface PatchItemResourceVenuePatchRequest {
    id: string;
    venueRequestBody: VenueRequestBody;
}

export interface PostCollectionResourceVenuePostRequest {
    venueRequestBody: VenueRequestBody;
}

export interface PutItemResourceVenuePutRequest {
    id: string;
    venueRequestBody: VenueRequestBody;
}

/**
 * 
 */
export class VenueEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-venue
     */
    async deleteItemResourceVenueDeleteRaw(requestParameters: DeleteItemResourceVenueDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceVenueDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/venues/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-venue
     */
    async deleteItemResourceVenueDelete(requestParameters: DeleteItemResourceVenueDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceVenueDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-venue
     */
    async getCollectionResourceVenueGet1Raw(requestParameters: GetCollectionResourceVenueGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelVenue>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/venues`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelVenueFromJSON(jsonValue));
    }

    /**
     * get-venue
     */
    async getCollectionResourceVenueGet1(requestParameters: GetCollectionResourceVenueGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelVenue> {
        const response = await this.getCollectionResourceVenueGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-venue
     */
    async getItemResourceVenueGetRaw(requestParameters: GetItemResourceVenueGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelVenue>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceVenueGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/venues/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelVenueFromJSON(jsonValue));
    }

    /**
     * get-venue
     */
    async getItemResourceVenueGet(requestParameters: GetItemResourceVenueGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelVenue> {
        const response = await this.getItemResourceVenueGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-venue
     */
    async patchItemResourceVenuePatchRaw(requestParameters: PatchItemResourceVenuePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelVenue>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceVenuePatch().'
            );
        }

        if (requestParameters['venueRequestBody'] == null) {
            throw new runtime.RequiredError(
                'venueRequestBody',
                'Required parameter "venueRequestBody" was null or undefined when calling patchItemResourceVenuePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/venues/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: VenueRequestBodyToJSON(requestParameters['venueRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelVenueFromJSON(jsonValue));
    }

    /**
     * patch-venue
     */
    async patchItemResourceVenuePatch(requestParameters: PatchItemResourceVenuePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelVenue | null | undefined > {
        const response = await this.patchItemResourceVenuePatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-venue
     */
    async postCollectionResourceVenuePostRaw(requestParameters: PostCollectionResourceVenuePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelVenue>> {
        if (requestParameters['venueRequestBody'] == null) {
            throw new runtime.RequiredError(
                'venueRequestBody',
                'Required parameter "venueRequestBody" was null or undefined when calling postCollectionResourceVenuePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/venues`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VenueRequestBodyToJSON(requestParameters['venueRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelVenueFromJSON(jsonValue));
    }

    /**
     * create-venue
     */
    async postCollectionResourceVenuePost(requestParameters: PostCollectionResourceVenuePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelVenue> {
        const response = await this.postCollectionResourceVenuePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-venue
     */
    async putItemResourceVenuePutRaw(requestParameters: PutItemResourceVenuePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelVenue>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceVenuePut().'
            );
        }

        if (requestParameters['venueRequestBody'] == null) {
            throw new runtime.RequiredError(
                'venueRequestBody',
                'Required parameter "venueRequestBody" was null or undefined when calling putItemResourceVenuePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/venues/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VenueRequestBodyToJSON(requestParameters['venueRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelVenueFromJSON(jsonValue));
    }

    /**
     * update-venue
     */
    async putItemResourceVenuePut(requestParameters: PutItemResourceVenuePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelVenue | null | undefined > {
        const response = await this.putItemResourceVenuePutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
