/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetVenueById404Response,
  GetVenueById422Response,
  GlobalErrorResponse,
  VenueDTO,
} from '../models/index';
import {
    GetVenueById404ResponseFromJSON,
    GetVenueById404ResponseToJSON,
    GetVenueById422ResponseFromJSON,
    GetVenueById422ResponseToJSON,
    GlobalErrorResponseFromJSON,
    GlobalErrorResponseToJSON,
    VenueDTOFromJSON,
    VenueDTOToJSON,
} from '../models/index';

export interface AddEmployeeRequest {
    id: number;
    employeeId: number;
}

export interface CreateVenueRequest {
    venueDTO: VenueDTO;
}

export interface DeleteVenueRequest {
    id: number;
}

export interface GetVenueByIdRequest {
    id: number;
}

export interface PatchVenueRequest {
    id: number;
    requestBody: { [key: string]: object; };
}

export interface RemoveEmployeeRequest {
    id: number;
    employeeId: number;
}

export interface UpdateVenueRequest {
    id: number;
    venueDTO: VenueDTO;
}

/**
 * 
 */
export class VenueControllerApi extends runtime.BaseAPI {

    /**
     */
    async addEmployeeRaw(requestParameters: AddEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VenueDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addEmployee().'
            );
        }

        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling addEmployee().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/venues/{id}/employees/{employeeId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"employeeId"}}`, encodeURIComponent(String(requestParameters['employeeId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VenueDTOFromJSON(jsonValue));
    }

    /**
     */
    async addEmployee(requestParameters: AddEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VenueDTO> {
        const response = await this.addEmployeeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createVenueRaw(requestParameters: CreateVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['venueDTO'] == null) {
            throw new runtime.RequiredError(
                'venueDTO',
                'Required parameter "venueDTO" was null or undefined when calling createVenue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/venues`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VenueDTOToJSON(requestParameters['venueDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createVenue(requestParameters: CreateVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createVenueRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteVenueRaw(requestParameters: DeleteVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteVenue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/venues/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteVenue(requestParameters: DeleteVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteVenueRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllVenuesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VenueDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/venues`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VenueDTOFromJSON));
    }

    /**
     */
    async getAllVenues(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VenueDTO>> {
        const response = await this.getAllVenuesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getVenueByIdRaw(requestParameters: GetVenueByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VenueDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVenueById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/venues/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VenueDTOFromJSON(jsonValue));
    }

    /**
     */
    async getVenueById(requestParameters: GetVenueByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VenueDTO> {
        const response = await this.getVenueByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async patchVenueRaw(requestParameters: PatchVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VenueDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchVenue().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling patchVenue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/venues/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VenueDTOFromJSON(jsonValue));
    }

    /**
     */
    async patchVenue(requestParameters: PatchVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VenueDTO> {
        const response = await this.patchVenueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async removeEmployeeRaw(requestParameters: RemoveEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VenueDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeEmployee().'
            );
        }

        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling removeEmployee().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/venues/{id}/remove_employees/{employeeId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"employeeId"}}`, encodeURIComponent(String(requestParameters['employeeId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VenueDTOFromJSON(jsonValue));
    }

    /**
     */
    async removeEmployee(requestParameters: RemoveEmployeeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VenueDTO> {
        const response = await this.removeEmployeeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateVenueRaw(requestParameters: UpdateVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VenueDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateVenue().'
            );
        }

        if (requestParameters['venueDTO'] == null) {
            throw new runtime.RequiredError(
                'venueDTO',
                'Required parameter "venueDTO" was null or undefined when calling updateVenue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/venues/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VenueDTOToJSON(requestParameters['venueDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VenueDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateVenue(requestParameters: UpdateVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VenueDTO> {
        const response = await this.updateVenueRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
