:snippetCurlGetAll: curl-request,response-body,http-request,http-response
:snippetCurlGet: path-parameters,curl-request,response-body,http-request,http-response
:snippetCurlPost: curl-request,request-body,request-fields,http-request,http-response
:snippetCurlUpdate: path-parameters,curl-request,request-body,response-body,http-request,http-response
:snippetCurlDelete: path-parameters,curl-request,http-request,http-response

==== Booking

===== GET All Bookings
operation::booking-get[snippets='{snippetCurlGetAll},response-fields']

===== GET Booking by id
operation::booking-get-by-id[snippets='{snippetCurlGet}']

===== POST Booking for Customer
operation::booking-create-for-customer-id[snippets='{snippetCurlPost}']

===== POST Reservation to Booking
operation::booking-add-reservation-to-booking[snippets='{snippetCurlPost}']

===== DELETE Reservation from Booking
operation::booking-delete-reservation-from-booking[snippets='{snippetCurlDelete}']

===== DELETE Booking by id
operation::booking-delete-by-id[snippets='{snippetCurlDelete}']


==== Ticket Reservation

===== GET All Ticket Reservations
operation::ticketReservation-get[snippets='{snippetCurlGetAll},response-fields']

===== GET Ticket Reservation by id
operation::ticketReservation-getById[snippets='{snippetCurlGet}']

===== POST Ticket Reservation
operation::ticketReservation-create[snippets='{snippetCurlPost}']