:snippetCurlGetAll: curl-request,response-body,http-request,http-response
:snippetCurlGet: path-parameters,curl-request,response-body,http-request,http-response
:snippetCurlPost: curl-request,request-body,request-fields,http-request,http-response
:snippetCurlUpdate: path-parameters,curl-request,request-body,response-body,http-request,http-response
:snippetCurlDelete: path-parameters,curl-request,http-request,http-response

==== Employees

===== GET All Employees
operation::employees-get[snippets='{snippetCurlGetAll}']

===== GET Employee by ID
operation::employees-get-by-id[snippets='{snippetCurlGet}']

===== GET Employee by ID - don't show password
operation::employees-get-by-id-no-pwd[snippets='{snippetCurlGet}']

===== POST Employee
operation::employees-create[snippets='{snippetCurlPost}']

===== PUT Employee by ID
operation::employees-put[snippets='{snippetCurlUpdate}']

===== PATCH Employee by ID
operation::employees-patch[snippets='{snippetCurlUpdate}']

===== DELETE Employee by ID
operation::employees-delete-by-id[snippets='{snippetCurlDelete}']


==== Customers
This is a simple example of a Customer documentation. It is accurate but not complete.


===== GET All Customers
operation::customers-get[snippets='{snippetCurlGetAll}']

===== GET Customer by ID
operation::customer-get-by-id[snippets='{snippetCurlGet}']

===== POST Customer
operation::customer-create[snippets='{snippetCurlPost}']

===== DELETE Customer by ID
operation::customer-delete-by-id[snippets='{snippetCurlDelete}']