# Configuration file for Dev environment
spring:
  debug: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:eventhubserver
    name: eventhubserver
    username: vi
  sql:
    init:
      encoding: UTF-8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    validateMigrationNaming: true
    validateOnMigrate: true
    baselineOnMigrate: true
    locations: classpath:db/migration
  management:
    endpoints:
      web:
        exposure:
          include: '*'
  logging:
    level:
      org.springframework: INFO
  output:
    ansi:
      enabled: ALWAYS
  server:
    compression:
      enabled: true
      mime-types: application/json,text/css,application/javascript
      min-response-size: 2048
