/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    '[id]': typeof import('./src/pages/venues/[id].vue')['default']
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    AiChatbotView: typeof import('./src/views/AiChatbotView.vue')['default']
    ApiDocView: typeof import('./src/views/ApiDocView.vue')['default']
    App: typeof import('./src/App.vue')['default']
    Customers: typeof import('./src/pages/customers/index.vue')['default']
    EmployeeView: typeof import('./src/views/EmployeeView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PageNotFoundView: typeof import('./src/views/PageNotFoundView.vue')['default']
    Pages: typeof import('./src/pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartLink: typeof import('./src/components/SmartLink.vue')['default']
    TheChatBot: typeof import('./src/components/TheChatBot.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheNavigation: typeof import('./src/components/TheNavigation.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TicketReservationView: typeof import('./src/views/ticketReservationView.vue')['default']
    Venues: typeof import('./src/pages/venues/index.vue')['default']
  }
}
