/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressDTO
 */
export interface AddressDTO {
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    zipcode?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    country?: string;
}

/**
 * Check if a given object implements the AddressDTO interface.
 */
export function instanceOfAddressDTO(value: object): value is AddressDTO {
    return true;
}

export function AddressDTOFromJSON(json: any): AddressDTO {
    return AddressDTOFromJSONTyped(json, false);
}

export function AddressDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'street': json['street'] == null ? undefined : json['street'],
        'city': json['city'] == null ? undefined : json['city'],
        'zipcode': json['zipcode'] == null ? undefined : json['zipcode'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function AddressDTOToJSON(json: any): AddressDTO {
    return AddressDTOToJSONTyped(json, false);
}

export function AddressDTOToJSONTyped(value?: AddressDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'street': value['street'],
        'city': value['city'],
        'zipcode': value['zipcode'],
        'country': value['country'],
    };
}

