/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Customer } from './Customer';
import {
    CustomerFromJSON,
    CustomerFromJSONTyped,
    CustomerToJSON,
    CustomerToJSONTyped,
} from './Customer';
import type { TicketReservation } from './TicketReservation';
import {
    TicketReservationFromJSON,
    TicketReservationFromJSONTyped,
    TicketReservationToJSON,
    TicketReservationToJSONTyped,
} from './TicketReservation';

/**
 * 
 * @export
 * @interface BookingDTO
 */
export interface BookingDTO {
    /**
     * 
     * @type {number}
     * @memberof BookingDTO
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof BookingDTO
     */
    bookingCreationTimestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof BookingDTO
     */
    totalPriceHt?: number;
    /**
     * 
     * @type {Customer}
     * @memberof BookingDTO
     */
    customer?: Customer;
    /**
     * 
     * @type {Set<TicketReservation>}
     * @memberof BookingDTO
     */
    reservations?: Set<TicketReservation>;
}

/**
 * Check if a given object implements the BookingDTO interface.
 */
export function instanceOfBookingDTO(value: object): value is BookingDTO {
    return true;
}

export function BookingDTOFromJSON(json: any): BookingDTO {
    return BookingDTOFromJSONTyped(json, false);
}

export function BookingDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'bookingCreationTimestamp': json['bookingCreationTimestamp'] == null ? undefined : (new Date(json['bookingCreationTimestamp'])),
        'totalPriceHt': json['totalPriceHt'] == null ? undefined : json['totalPriceHt'],
        'customer': json['customer'] == null ? undefined : CustomerFromJSON(json['customer']),
        'reservations': json['reservations'] == null ? undefined : (new Set((json['reservations'] as Array<any>).map(TicketReservationFromJSON))),
    };
}

export function BookingDTOToJSON(json: any): BookingDTO {
    return BookingDTOToJSONTyped(json, false);
}

export function BookingDTOToJSONTyped(value?: BookingDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bookingCreationTimestamp': value['bookingCreationTimestamp'] == null ? undefined : ((value['bookingCreationTimestamp']).toISOString()),
        'totalPriceHt': value['totalPriceHt'],
        'customer': CustomerToJSON(value['customer']),
        'reservations': value['reservations'] == null ? undefined : (Array.from(value['reservations'] as Set<any>).map(TicketReservationToJSON)),
    };
}

