/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategorySpatialDTO
 */
export interface CategorySpatialDTO {
    /**
     * 
     * @type {number}
     * @memberof CategorySpatialDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CategorySpatialDTO
     */
    name?: string;
}

/**
 * Check if a given object implements the CategorySpatialDTO interface.
 */
export function instanceOfCategorySpatialDTO(value: object): value is CategorySpatialDTO {
    return true;
}

export function CategorySpatialDTOFromJSON(json: any): CategorySpatialDTO {
    return CategorySpatialDTOFromJSONTyped(json, false);
}

export function CategorySpatialDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategorySpatialDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CategorySpatialDTOToJSON(json: any): CategorySpatialDTO {
    return CategorySpatialDTOToJSONTyped(json, false);
}

export function CategorySpatialDTOToJSONTyped(value?: CategorySpatialDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

