/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryTariffRequestBody
 */
export interface CategoryTariffRequestBody {
    /**
     * 
     * @type {number}
     * @memberof CategoryTariffRequestBody
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryTariffRequestBody
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryTariffRequestBody
     */
    tarification?: string;
}

/**
 * Check if a given object implements the CategoryTariffRequestBody interface.
 */
export function instanceOfCategoryTariffRequestBody(value: object): value is CategoryTariffRequestBody {
    return true;
}

export function CategoryTariffRequestBodyFromJSON(json: any): CategoryTariffRequestBody {
    return CategoryTariffRequestBodyFromJSONTyped(json, false);
}

export function CategoryTariffRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryTariffRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'tarification': json['tarification'] == null ? undefined : json['tarification'],
    };
}

export function CategoryTariffRequestBodyToJSON(json: any): CategoryTariffRequestBody {
    return CategoryTariffRequestBodyToJSONTyped(json, false);
}

export function CategoryTariffRequestBodyToJSONTyped(value?: CategoryTariffRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'tarification': value['tarification'],
    };
}

