/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategorySpatialRequestBody
 */
export interface CategorySpatialRequestBody {
    /**
     * 
     * @type {number}
     * @memberof CategorySpatialRequestBody
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CategorySpatialRequestBody
     */
    name?: string;
}

/**
 * Check if a given object implements the CategorySpatialRequestBody interface.
 */
export function instanceOfCategorySpatialRequestBody(value: object): value is CategorySpatialRequestBody {
    return true;
}

export function CategorySpatialRequestBodyFromJSON(json: any): CategorySpatialRequestBody {
    return CategorySpatialRequestBodyFromJSONTyped(json, false);
}

export function CategorySpatialRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategorySpatialRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CategorySpatialRequestBodyToJSON(json: any): CategorySpatialRequestBody {
    return CategorySpatialRequestBodyToJSONTyped(json, false);
}

export function CategorySpatialRequestBodyToJSONTyped(value?: CategorySpatialRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

