/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedModelEntityModelSessionEventEmbedded } from './PagedModelEntityModelSessionEventEmbedded';
import {
    PagedModelEntityModelSessionEventEmbeddedFromJSON,
    PagedModelEntityModelSessionEventEmbeddedFromJSONTyped,
    PagedModelEntityModelSessionEventEmbeddedToJSON,
    PagedModelEntityModelSessionEventEmbeddedToJSONTyped,
} from './PagedModelEntityModelSessionEventEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CollectionModelEntityModelSessionEvent
 */
export interface CollectionModelEntityModelSessionEvent {
    /**
     * 
     * @type {PagedModelEntityModelSessionEventEmbedded}
     * @memberof CollectionModelEntityModelSessionEvent
     */
    embedded?: PagedModelEntityModelSessionEventEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CollectionModelEntityModelSessionEvent
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the CollectionModelEntityModelSessionEvent interface.
 */
export function instanceOfCollectionModelEntityModelSessionEvent(value: object): value is CollectionModelEntityModelSessionEvent {
    return true;
}

export function CollectionModelEntityModelSessionEventFromJSON(json: any): CollectionModelEntityModelSessionEvent {
    return CollectionModelEntityModelSessionEventFromJSONTyped(json, false);
}

export function CollectionModelEntityModelSessionEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelEntityModelSessionEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelSessionEventEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function CollectionModelEntityModelSessionEventToJSON(json: any): CollectionModelEntityModelSessionEvent {
    return CollectionModelEntityModelSessionEventToJSONTyped(json, false);
}

export function CollectionModelEntityModelSessionEventToJSONTyped(value?: CollectionModelEntityModelSessionEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelSessionEventEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

