/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionModelTicketReservationEmbedded } from './CollectionModelTicketReservationEmbedded';
import {
    CollectionModelTicketReservationEmbeddedFromJSON,
    CollectionModelTicketReservationEmbeddedFromJSONTyped,
    CollectionModelTicketReservationEmbeddedToJSON,
    CollectionModelTicketReservationEmbeddedToJSONTyped,
} from './CollectionModelTicketReservationEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CollectionModelTicketReservation
 */
export interface CollectionModelTicketReservation {
    /**
     * 
     * @type {CollectionModelTicketReservationEmbedded}
     * @memberof CollectionModelTicketReservation
     */
    embedded?: CollectionModelTicketReservationEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CollectionModelTicketReservation
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the CollectionModelTicketReservation interface.
 */
export function instanceOfCollectionModelTicketReservation(value: object): value is CollectionModelTicketReservation {
    return true;
}

export function CollectionModelTicketReservationFromJSON(json: any): CollectionModelTicketReservation {
    return CollectionModelTicketReservationFromJSONTyped(json, false);
}

export function CollectionModelTicketReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelTicketReservation {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : CollectionModelTicketReservationEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function CollectionModelTicketReservationToJSON(json: any): CollectionModelTicketReservation {
    return CollectionModelTicketReservationToJSONTyped(json, false);
}

export function CollectionModelTicketReservationToJSONTyped(value?: CollectionModelTicketReservation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': CollectionModelTicketReservationEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

