/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionModelEmployeeEmbedded } from './CollectionModelEmployeeEmbedded';
import {
    CollectionModelEmployeeEmbeddedFromJSON,
    CollectionModelEmployeeEmbeddedFromJSONTyped,
    CollectionModelEmployeeEmbeddedToJSON,
    CollectionModelEmployeeEmbeddedToJSONTyped,
} from './CollectionModelEmployeeEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CollectionModelEmployee
 */
export interface CollectionModelEmployee {
    /**
     * 
     * @type {CollectionModelEmployeeEmbedded}
     * @memberof CollectionModelEmployee
     */
    embedded?: CollectionModelEmployeeEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CollectionModelEmployee
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the CollectionModelEmployee interface.
 */
export function instanceOfCollectionModelEmployee(value: object): value is CollectionModelEmployee {
    return true;
}

export function CollectionModelEmployeeFromJSON(json: any): CollectionModelEmployee {
    return CollectionModelEmployeeFromJSONTyped(json, false);
}

export function CollectionModelEmployeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelEmployee {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : CollectionModelEmployeeEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function CollectionModelEmployeeToJSON(json: any): CollectionModelEmployee {
    return CollectionModelEmployeeToJSONTyped(json, false);
}

export function CollectionModelEmployeeToJSONTyped(value?: CollectionModelEmployee | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': CollectionModelEmployeeEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

