/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigurationHallRequestBody
 */
export interface ConfigurationHallRequestBody {
    /**
     * 
     * @type {number}
     * @memberof ConfigurationHallRequestBody
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationHallRequestBody
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigurationHallRequestBody
     */
    capacityOfConfiguration?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationHallRequestBody
     */
    hall?: string;
}

/**
 * Check if a given object implements the ConfigurationHallRequestBody interface.
 */
export function instanceOfConfigurationHallRequestBody(value: object): value is ConfigurationHallRequestBody {
    return true;
}

export function ConfigurationHallRequestBodyFromJSON(json: any): ConfigurationHallRequestBody {
    return ConfigurationHallRequestBodyFromJSONTyped(json, false);
}

export function ConfigurationHallRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationHallRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'capacityOfConfiguration': json['capacityOfConfiguration'] == null ? undefined : json['capacityOfConfiguration'],
        'hall': json['hall'] == null ? undefined : json['hall'],
    };
}

export function ConfigurationHallRequestBodyToJSON(json: any): ConfigurationHallRequestBody {
    return ConfigurationHallRequestBodyToJSONTyped(json, false);
}

export function ConfigurationHallRequestBodyToJSONTyped(value?: ConfigurationHallRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'capacityOfConfiguration': value['capacityOfConfiguration'],
        'hall': value['hall'],
    };
}

