/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressDTO } from './AddressDTO';
import {
    AddressDTOFromJSON,
    AddressDTOFromJSONTyped,
    AddressDTOToJSON,
    AddressDTOToJSONTyped,
} from './AddressDTO';

/**
 * 
 * @export
 * @interface CustomerDTO
 */
export interface CustomerDTO {
    /**
     * 
     * @type {number}
     * @memberof CustomerDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerDTO
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerDTO
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerDTO
     */
    phoneNumber?: string;
    /**
     * 
     * @type {AddressDTO}
     * @memberof CustomerDTO
     */
    address?: AddressDTO;
    /**
     * 
     * @type {string}
     * @memberof CustomerDTO
     */
    creditCardNumber?: string;
}

/**
 * Check if a given object implements the CustomerDTO interface.
 */
export function instanceOfCustomerDTO(value: object): value is CustomerDTO {
    return true;
}

export function CustomerDTOFromJSON(json: any): CustomerDTO {
    return CustomerDTOFromJSONTyped(json, false);
}

export function CustomerDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'address': json['address'] == null ? undefined : AddressDTOFromJSON(json['address']),
        'creditCardNumber': json['creditCardNumber'] == null ? undefined : json['creditCardNumber'],
    };
}

export function CustomerDTOToJSON(json: any): CustomerDTO {
    return CustomerDTOToJSONTyped(json, false);
}

export function CustomerDTOToJSONTyped(value?: CustomerDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'username': value['username'],
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'address': AddressDTOToJSON(value['address']),
        'creditCardNumber': value['creditCardNumber'],
    };
}

