/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * 
 * @export
 * @interface CustomerRequestBody
 */
export interface CustomerRequestBody {
    /**
     * 
     * @type {number}
     * @memberof CustomerRequestBody
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerRequestBody
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerRequestBody
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerRequestBody
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerRequestBody
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerRequestBody
     */
    phoneNumber?: string;
    /**
     * 
     * @type {Address}
     * @memberof CustomerRequestBody
     */
    address?: Address;
    /**
     * 
     * @type {string}
     * @memberof CustomerRequestBody
     */
    creditCardNumber?: string;
}

/**
 * Check if a given object implements the CustomerRequestBody interface.
 */
export function instanceOfCustomerRequestBody(value: object): value is CustomerRequestBody {
    return true;
}

export function CustomerRequestBodyFromJSON(json: any): CustomerRequestBody {
    return CustomerRequestBodyFromJSONTyped(json, false);
}

export function CustomerRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'creditCardNumber': json['creditCardNumber'] == null ? undefined : json['creditCardNumber'],
    };
}

export function CustomerRequestBodyToJSON(json: any): CustomerRequestBody {
    return CustomerRequestBodyToJSONTyped(json, false);
}

export function CustomerRequestBodyToJSONTyped(value?: CustomerRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'username': value['username'],
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'address': AddressToJSON(value['address']),
        'creditCardNumber': value['creditCardNumber'],
    };
}

