/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmployeeDTONoPwd
 */
export interface EmployeeDTONoPwd {
    /**
     * 
     * @type {number}
     * @memberof EmployeeDTONoPwd
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTONoPwd
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTONoPwd
     */
    email?: string;
}

/**
 * Check if a given object implements the EmployeeDTONoPwd interface.
 */
export function instanceOfEmployeeDTONoPwd(value: object): value is EmployeeDTONoPwd {
    return true;
}

export function EmployeeDTONoPwdFromJSON(json: any): EmployeeDTONoPwd {
    return EmployeeDTONoPwdFromJSONTyped(json, false);
}

export function EmployeeDTONoPwdFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeDTONoPwd {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function EmployeeDTONoPwdToJSON(json: any): EmployeeDTONoPwd {
    return EmployeeDTONoPwdToJSONTyped(json, false);
}

export function EmployeeDTONoPwdToJSONTyped(value?: EmployeeDTONoPwd | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
    };
}

