/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface EntityModelEvent
 */
export interface EntityModelEvent {
    /**
     * 
     * @type {string}
     * @memberof EntityModelEvent
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelEvent
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelEvent
     */
    dateStart?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelEvent
     */
    dateEnd?: Date;
    /**
     * 
     * @type {string}
     * @memberof EntityModelEvent
     */
    closedDay?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelEvent
     */
    imageUrl?: string;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof EntityModelEvent
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the EntityModelEvent interface.
 */
export function instanceOfEntityModelEvent(value: object): value is EntityModelEvent {
    return true;
}

export function EntityModelEventFromJSON(json: any): EntityModelEvent {
    return EntityModelEventFromJSONTyped(json, false);
}

export function EntityModelEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityModelEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'dateStart': json['dateStart'] == null ? undefined : (new Date(json['dateStart'])),
        'dateEnd': json['dateEnd'] == null ? undefined : (new Date(json['dateEnd'])),
        'closedDay': json['closedDay'] == null ? undefined : json['closedDay'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function EntityModelEventToJSON(json: any): EntityModelEvent {
    return EntityModelEventToJSONTyped(json, false);
}

export function EntityModelEventToJSONTyped(value?: EntityModelEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'dateStart': value['dateStart'] == null ? undefined : ((value['dateStart']).toISOString().substring(0,10)),
        'dateEnd': value['dateEnd'] == null ? undefined : ((value['dateEnd']).toISOString().substring(0,10)),
        'closedDay': value['closedDay'],
        'imageUrl': value['imageUrl'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

