/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface EntityModelPaymentStatus
 */
export interface EntityModelPaymentStatus {
    /**
     * 
     * @type {string}
     * @memberof EntityModelPaymentStatus
     */
    paymentStatusName?: string;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof EntityModelPaymentStatus
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the EntityModelPaymentStatus interface.
 */
export function instanceOfEntityModelPaymentStatus(value: object): value is EntityModelPaymentStatus {
    return true;
}

export function EntityModelPaymentStatusFromJSON(json: any): EntityModelPaymentStatus {
    return EntityModelPaymentStatusFromJSONTyped(json, false);
}

export function EntityModelPaymentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityModelPaymentStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentStatusName': json['paymentStatusName'] == null ? undefined : json['paymentStatusName'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function EntityModelPaymentStatusToJSON(json: any): EntityModelPaymentStatus {
    return EntityModelPaymentStatusToJSONTyped(json, false);
}

export function EntityModelPaymentStatusToJSONTyped(value?: EntityModelPaymentStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentStatusName': value['paymentStatusName'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

