/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface EntityModelSeat
 */
export interface EntityModelSeat {
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelSeat
     */
    isSeated?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EntityModelSeat
     */
    rowNo?: string;
    /**
     * 
     * @type {number}
     * @memberof EntityModelSeat
     */
    seatNo?: number;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof EntityModelSeat
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the EntityModelSeat interface.
 */
export function instanceOfEntityModelSeat(value: object): value is EntityModelSeat {
    return true;
}

export function EntityModelSeatFromJSON(json: any): EntityModelSeat {
    return EntityModelSeatFromJSONTyped(json, false);
}

export function EntityModelSeatFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityModelSeat {
    if (json == null) {
        return json;
    }
    return {
        
        'isSeated': json['isSeated'] == null ? undefined : json['isSeated'],
        'rowNo': json['rowNo'] == null ? undefined : json['rowNo'],
        'seatNo': json['seatNo'] == null ? undefined : json['seatNo'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function EntityModelSeatToJSON(json: any): EntityModelSeat {
    return EntityModelSeatToJSONTyped(json, false);
}

export function EntityModelSeatToJSONTyped(value?: EntityModelSeat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isSeated': value['isSeated'],
        'rowNo': value['rowNo'],
        'seatNo': value['seatNo'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

