/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface EntityModelPayment
 */
export interface EntityModelPayment {
    /**
     * 
     * @type {Date}
     * @memberof EntityModelPayment
     */
    paymentDateTime?: Date;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof EntityModelPayment
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the EntityModelPayment interface.
 */
export function instanceOfEntityModelPayment(value: object): value is EntityModelPayment {
    return true;
}

export function EntityModelPaymentFromJSON(json: any): EntityModelPayment {
    return EntityModelPaymentFromJSONTyped(json, false);
}

export function EntityModelPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityModelPayment {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentDateTime': json['paymentDateTime'] == null ? undefined : (new Date(json['paymentDateTime'])),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function EntityModelPaymentToJSON(json: any): EntityModelPayment {
    return EntityModelPaymentToJSONTyped(json, false);
}

export function EntityModelPaymentToJSONTyped(value?: EntityModelPayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentDateTime': value['paymentDateTime'] == null ? undefined : ((value['paymentDateTime']).toISOString()),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

