/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface EntityModelTarification
 */
export interface EntityModelTarification {
    /**
     * 
     * @type {number}
     * @memberof EntityModelTarification
     */
    basePrice?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelTarification
     */
    taxeRate?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelTarification
     */
    discountStudentRate?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelTarification
     */
    discountSeniorRate?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelTarification
     */
    discountChildRate?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelTarification
     */
    discountUnemployedRate?: number;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof EntityModelTarification
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the EntityModelTarification interface.
 */
export function instanceOfEntityModelTarification(value: object): value is EntityModelTarification {
    return true;
}

export function EntityModelTarificationFromJSON(json: any): EntityModelTarification {
    return EntityModelTarificationFromJSONTyped(json, false);
}

export function EntityModelTarificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityModelTarification {
    if (json == null) {
        return json;
    }
    return {
        
        'basePrice': json['basePrice'] == null ? undefined : json['basePrice'],
        'taxeRate': json['taxeRate'] == null ? undefined : json['taxeRate'],
        'discountStudentRate': json['discountStudentRate'] == null ? undefined : json['discountStudentRate'],
        'discountSeniorRate': json['discountSeniorRate'] == null ? undefined : json['discountSeniorRate'],
        'discountChildRate': json['discountChildRate'] == null ? undefined : json['discountChildRate'],
        'discountUnemployedRate': json['discountUnemployedRate'] == null ? undefined : json['discountUnemployedRate'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function EntityModelTarificationToJSON(json: any): EntityModelTarification {
    return EntityModelTarificationToJSONTyped(json, false);
}

export function EntityModelTarificationToJSONTyped(value?: EntityModelTarification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'basePrice': value['basePrice'],
        'taxeRate': value['taxeRate'],
        'discountStudentRate': value['discountStudentRate'],
        'discountSeniorRate': value['discountSeniorRate'],
        'discountChildRate': value['discountChildRate'],
        'discountUnemployedRate': value['discountUnemployedRate'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

