/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface EntityModelEmployee
 */
export interface EntityModelEmployee {
    /**
     * 
     * @type {string}
     * @memberof EntityModelEmployee
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelEmployee
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelEmployee
     */
    email: string;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof EntityModelEmployee
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the EntityModelEmployee interface.
 */
export function instanceOfEntityModelEmployee(value: object): value is EntityModelEmployee {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function EntityModelEmployeeFromJSON(json: any): EntityModelEmployee {
    return EntityModelEmployeeFromJSONTyped(json, false);
}

export function EntityModelEmployeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityModelEmployee {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'email': json['email'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function EntityModelEmployeeToJSON(json: any): EntityModelEmployee {
    return EntityModelEmployeeToJSONTyped(json, false);
}

export function EntityModelEmployeeToJSONTyped(value?: EntityModelEmployee | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
        'email': value['email'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

