/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface EntityModelBooking
 */
export interface EntityModelBooking {
    /**
     * 
     * @type {Date}
     * @memberof EntityModelBooking
     */
    bookingCreationTimestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof EntityModelBooking
     */
    totalPriceHt?: number;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof EntityModelBooking
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the EntityModelBooking interface.
 */
export function instanceOfEntityModelBooking(value: object): value is EntityModelBooking {
    return true;
}

export function EntityModelBookingFromJSON(json: any): EntityModelBooking {
    return EntityModelBookingFromJSONTyped(json, false);
}

export function EntityModelBookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityModelBooking {
    if (json == null) {
        return json;
    }
    return {
        
        'bookingCreationTimestamp': json['bookingCreationTimestamp'] == null ? undefined : (new Date(json['bookingCreationTimestamp'])),
        'totalPriceHt': json['totalPriceHt'] == null ? undefined : json['totalPriceHt'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function EntityModelBookingToJSON(json: any): EntityModelBooking {
    return EntityModelBookingToJSONTyped(json, false);
}

export function EntityModelBookingToJSONTyped(value?: EntityModelBooking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookingCreationTimestamp': value['bookingCreationTimestamp'] == null ? undefined : ((value['bookingCreationTimestamp']).toISOString()),
        'totalPriceHt': value['totalPriceHt'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

