/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventDTO
 */
export interface EventDTO {
    /**
     * 
     * @type {number}
     * @memberof EventDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof EventDTO
     */
    dateStart?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EventDTO
     */
    dateEnd?: Date;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    closedDay?: string;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the EventDTO interface.
 */
export function instanceOfEventDTO(value: object): value is EventDTO {
    return true;
}

export function EventDTOFromJSON(json: any): EventDTO {
    return EventDTOFromJSONTyped(json, false);
}

export function EventDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'dateStart': json['dateStart'] == null ? undefined : (new Date(json['dateStart'])),
        'dateEnd': json['dateEnd'] == null ? undefined : (new Date(json['dateEnd'])),
        'closedDay': json['closedDay'] == null ? undefined : json['closedDay'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
    };
}

export function EventDTOToJSON(json: any): EventDTO {
    return EventDTOToJSONTyped(json, false);
}

export function EventDTOToJSONTyped(value?: EventDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'dateStart': value['dateStart'] == null ? undefined : ((value['dateStart']).toISOString().substring(0,10)),
        'dateEnd': value['dateEnd'] == null ? undefined : ((value['dateEnd']).toISOString().substring(0,10)),
        'closedDay': value['closedDay'],
        'imageUrl': value['imageUrl'],
    };
}

