/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GlobalErrorResponse
 */
export interface GlobalErrorResponse {
    /**
     * 
     * @type {Date}
     * @memberof GlobalErrorResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GlobalErrorResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof GlobalErrorResponse
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalErrorResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the GlobalErrorResponse interface.
 */
export function instanceOfGlobalErrorResponse(value: object): value is GlobalErrorResponse {
    return true;
}

export function GlobalErrorResponseFromJSON(json: any): GlobalErrorResponse {
    return GlobalErrorResponseFromJSONTyped(json, false);
}

export function GlobalErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'path': json['path'] == null ? undefined : json['path'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GlobalErrorResponseToJSON(json: any): GlobalErrorResponse {
    return GlobalErrorResponseToJSONTyped(json, false);
}

export function GlobalErrorResponseToJSONTyped(value?: GlobalErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'statusCode': value['statusCode'],
        'path': value['path'],
        'message': value['message'],
    };
}

