/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelTicketReservation } from './EntityModelTicketReservation';
import {
    EntityModelTicketReservationFromJSON,
    EntityModelTicketReservationFromJSONTyped,
    EntityModelTicketReservationToJSON,
    EntityModelTicketReservationToJSONTyped,
} from './EntityModelTicketReservation';

/**
 * 
 * @export
 * @interface PagedModelEntityModelTicketReservationEmbedded
 */
export interface PagedModelEntityModelTicketReservationEmbedded {
    /**
     * 
     * @type {Array<EntityModelTicketReservation>}
     * @memberof PagedModelEntityModelTicketReservationEmbedded
     */
    ticketReservations?: Array<EntityModelTicketReservation>;
}

/**
 * Check if a given object implements the PagedModelEntityModelTicketReservationEmbedded interface.
 */
export function instanceOfPagedModelEntityModelTicketReservationEmbedded(value: object): value is PagedModelEntityModelTicketReservationEmbedded {
    return true;
}

export function PagedModelEntityModelTicketReservationEmbeddedFromJSON(json: any): PagedModelEntityModelTicketReservationEmbedded {
    return PagedModelEntityModelTicketReservationEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelTicketReservationEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelTicketReservationEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'ticketReservations': json['ticketReservations'] == null ? undefined : ((json['ticketReservations'] as Array<any>).map(EntityModelTicketReservationFromJSON)),
    };
}

export function PagedModelEntityModelTicketReservationEmbeddedToJSON(json: any): PagedModelEntityModelTicketReservationEmbedded {
    return PagedModelEntityModelTicketReservationEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelTicketReservationEmbeddedToJSONTyped(value?: PagedModelEntityModelTicketReservationEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ticketReservations': value['ticketReservations'] == null ? undefined : ((value['ticketReservations'] as Array<any>).map(EntityModelTicketReservationToJSON)),
    };
}

