/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { PagedModelEntityModelConfigurationHallEmbedded } from './PagedModelEntityModelConfigurationHallEmbedded';
import {
    PagedModelEntityModelConfigurationHallEmbeddedFromJSON,
    PagedModelEntityModelConfigurationHallEmbeddedFromJSONTyped,
    PagedModelEntityModelConfigurationHallEmbeddedToJSON,
    PagedModelEntityModelConfigurationHallEmbeddedToJSONTyped,
} from './PagedModelEntityModelConfigurationHallEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface PagedModelEntityModelConfigurationHall
 */
export interface PagedModelEntityModelConfigurationHall {
    /**
     * 
     * @type {PagedModelEntityModelConfigurationHallEmbedded}
     * @memberof PagedModelEntityModelConfigurationHall
     */
    embedded?: PagedModelEntityModelConfigurationHallEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelConfigurationHall
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelConfigurationHall
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelConfigurationHall interface.
 */
export function instanceOfPagedModelEntityModelConfigurationHall(value: object): value is PagedModelEntityModelConfigurationHall {
    return true;
}

export function PagedModelEntityModelConfigurationHallFromJSON(json: any): PagedModelEntityModelConfigurationHall {
    return PagedModelEntityModelConfigurationHallFromJSONTyped(json, false);
}

export function PagedModelEntityModelConfigurationHallFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelConfigurationHall {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelConfigurationHallEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelConfigurationHallToJSON(json: any): PagedModelEntityModelConfigurationHall {
    return PagedModelEntityModelConfigurationHallToJSONTyped(json, false);
}

export function PagedModelEntityModelConfigurationHallToJSONTyped(value?: PagedModelEntityModelConfigurationHall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelConfigurationHallEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

