/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedModelEntityModelCategoryTariffEmbedded } from './PagedModelEntityModelCategoryTariffEmbedded';
import {
    PagedModelEntityModelCategoryTariffEmbeddedFromJSON,
    PagedModelEntityModelCategoryTariffEmbeddedFromJSONTyped,
    PagedModelEntityModelCategoryTariffEmbeddedToJSON,
    PagedModelEntityModelCategoryTariffEmbeddedToJSONTyped,
} from './PagedModelEntityModelCategoryTariffEmbedded';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface PagedModelEntityModelCategoryTariff
 */
export interface PagedModelEntityModelCategoryTariff {
    /**
     * 
     * @type {PagedModelEntityModelCategoryTariffEmbedded}
     * @memberof PagedModelEntityModelCategoryTariff
     */
    embedded?: PagedModelEntityModelCategoryTariffEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelCategoryTariff
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelCategoryTariff
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelCategoryTariff interface.
 */
export function instanceOfPagedModelEntityModelCategoryTariff(value: object): value is PagedModelEntityModelCategoryTariff {
    return true;
}

export function PagedModelEntityModelCategoryTariffFromJSON(json: any): PagedModelEntityModelCategoryTariff {
    return PagedModelEntityModelCategoryTariffFromJSONTyped(json, false);
}

export function PagedModelEntityModelCategoryTariffFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelCategoryTariff {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelCategoryTariffEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelCategoryTariffToJSON(json: any): PagedModelEntityModelCategoryTariff {
    return PagedModelEntityModelCategoryTariffToJSONTyped(json, false);
}

export function PagedModelEntityModelCategoryTariffToJSONTyped(value?: PagedModelEntityModelCategoryTariff | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelCategoryTariffEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

