/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelVenue } from './EntityModelVenue';
import {
    EntityModelVenueFromJSON,
    EntityModelVenueFromJSONTyped,
    EntityModelVenueToJSON,
    EntityModelVenueToJSONTyped,
} from './EntityModelVenue';

/**
 * 
 * @export
 * @interface PagedModelEntityModelVenueEmbedded
 */
export interface PagedModelEntityModelVenueEmbedded {
    /**
     * 
     * @type {Array<EntityModelVenue>}
     * @memberof PagedModelEntityModelVenueEmbedded
     */
    venues?: Array<EntityModelVenue>;
}

/**
 * Check if a given object implements the PagedModelEntityModelVenueEmbedded interface.
 */
export function instanceOfPagedModelEntityModelVenueEmbedded(value: object): value is PagedModelEntityModelVenueEmbedded {
    return true;
}

export function PagedModelEntityModelVenueEmbeddedFromJSON(json: any): PagedModelEntityModelVenueEmbedded {
    return PagedModelEntityModelVenueEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelVenueEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelVenueEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'venues': json['venues'] == null ? undefined : ((json['venues'] as Array<any>).map(EntityModelVenueFromJSON)),
    };
}

export function PagedModelEntityModelVenueEmbeddedToJSON(json: any): PagedModelEntityModelVenueEmbedded {
    return PagedModelEntityModelVenueEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelVenueEmbeddedToJSONTyped(value?: PagedModelEntityModelVenueEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'venues': value['venues'] == null ? undefined : ((value['venues'] as Array<any>).map(EntityModelVenueToJSON)),
    };
}

