/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';
import type { PagedModelEntityModelHallEmbedded } from './PagedModelEntityModelHallEmbedded';
import {
    PagedModelEntityModelHallEmbeddedFromJSON,
    PagedModelEntityModelHallEmbeddedFromJSONTyped,
    PagedModelEntityModelHallEmbeddedToJSON,
    PagedModelEntityModelHallEmbeddedToJSONTyped,
} from './PagedModelEntityModelHallEmbedded';

/**
 * 
 * @export
 * @interface PagedModelEntityModelHall
 */
export interface PagedModelEntityModelHall {
    /**
     * 
     * @type {PagedModelEntityModelHallEmbedded}
     * @memberof PagedModelEntityModelHall
     */
    embedded?: PagedModelEntityModelHallEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelHall
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelHall
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelHall interface.
 */
export function instanceOfPagedModelEntityModelHall(value: object): value is PagedModelEntityModelHall {
    return true;
}

export function PagedModelEntityModelHallFromJSON(json: any): PagedModelEntityModelHall {
    return PagedModelEntityModelHallFromJSONTyped(json, false);
}

export function PagedModelEntityModelHallFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelHall {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelHallEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelHallToJSON(json: any): PagedModelEntityModelHall {
    return PagedModelEntityModelHallToJSONTyped(json, false);
}

export function PagedModelEntityModelHallToJSONTyped(value?: PagedModelEntityModelHall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelHallEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

