/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { PagedModelEntityModelTicketReservationEmbedded } from './PagedModelEntityModelTicketReservationEmbedded';
import {
    PagedModelEntityModelTicketReservationEmbeddedFromJSON,
    PagedModelEntityModelTicketReservationEmbeddedFromJSONTyped,
    PagedModelEntityModelTicketReservationEmbeddedToJSON,
    PagedModelEntityModelTicketReservationEmbeddedToJSONTyped,
} from './PagedModelEntityModelTicketReservationEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface PagedModelEntityModelTicketReservation
 */
export interface PagedModelEntityModelTicketReservation {
    /**
     * 
     * @type {PagedModelEntityModelTicketReservationEmbedded}
     * @memberof PagedModelEntityModelTicketReservation
     */
    embedded?: PagedModelEntityModelTicketReservationEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelTicketReservation
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelTicketReservation
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelTicketReservation interface.
 */
export function instanceOfPagedModelEntityModelTicketReservation(value: object): value is PagedModelEntityModelTicketReservation {
    return true;
}

export function PagedModelEntityModelTicketReservationFromJSON(json: any): PagedModelEntityModelTicketReservation {
    return PagedModelEntityModelTicketReservationFromJSONTyped(json, false);
}

export function PagedModelEntityModelTicketReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelTicketReservation {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelTicketReservationEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelTicketReservationToJSON(json: any): PagedModelEntityModelTicketReservation {
    return PagedModelEntityModelTicketReservationToJSONTyped(json, false);
}

export function PagedModelEntityModelTicketReservationToJSONTyped(value?: PagedModelEntityModelTicketReservation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelTicketReservationEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

