/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelPayment } from './EntityModelPayment';
import {
    EntityModelPaymentFromJSON,
    EntityModelPaymentFromJSONTyped,
    EntityModelPaymentToJSON,
    EntityModelPaymentToJSONTyped,
} from './EntityModelPayment';

/**
 * 
 * @export
 * @interface PagedModelEntityModelPaymentEmbedded
 */
export interface PagedModelEntityModelPaymentEmbedded {
    /**
     * 
     * @type {Array<EntityModelPayment>}
     * @memberof PagedModelEntityModelPaymentEmbedded
     */
    payments?: Array<EntityModelPayment>;
}

/**
 * Check if a given object implements the PagedModelEntityModelPaymentEmbedded interface.
 */
export function instanceOfPagedModelEntityModelPaymentEmbedded(value: object): value is PagedModelEntityModelPaymentEmbedded {
    return true;
}

export function PagedModelEntityModelPaymentEmbeddedFromJSON(json: any): PagedModelEntityModelPaymentEmbedded {
    return PagedModelEntityModelPaymentEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelPaymentEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelPaymentEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'payments': json['payments'] == null ? undefined : ((json['payments'] as Array<any>).map(EntityModelPaymentFromJSON)),
    };
}

export function PagedModelEntityModelPaymentEmbeddedToJSON(json: any): PagedModelEntityModelPaymentEmbedded {
    return PagedModelEntityModelPaymentEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelPaymentEmbeddedToJSONTyped(value?: PagedModelEntityModelPaymentEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payments': value['payments'] == null ? undefined : ((value['payments'] as Array<any>).map(EntityModelPaymentToJSON)),
    };
}

