/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelCustomer } from './EntityModelCustomer';
import {
    EntityModelCustomerFromJSON,
    EntityModelCustomerFromJSONTyped,
    EntityModelCustomerToJSON,
    EntityModelCustomerToJSONTyped,
} from './EntityModelCustomer';

/**
 * 
 * @export
 * @interface PagedModelEntityModelCustomerEmbedded
 */
export interface PagedModelEntityModelCustomerEmbedded {
    /**
     * 
     * @type {Array<EntityModelCustomer>}
     * @memberof PagedModelEntityModelCustomerEmbedded
     */
    customers?: Array<EntityModelCustomer>;
}

/**
 * Check if a given object implements the PagedModelEntityModelCustomerEmbedded interface.
 */
export function instanceOfPagedModelEntityModelCustomerEmbedded(value: object): value is PagedModelEntityModelCustomerEmbedded {
    return true;
}

export function PagedModelEntityModelCustomerEmbeddedFromJSON(json: any): PagedModelEntityModelCustomerEmbedded {
    return PagedModelEntityModelCustomerEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelCustomerEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelCustomerEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'customers': json['customers'] == null ? undefined : ((json['customers'] as Array<any>).map(EntityModelCustomerFromJSON)),
    };
}

export function PagedModelEntityModelCustomerEmbeddedToJSON(json: any): PagedModelEntityModelCustomerEmbedded {
    return PagedModelEntityModelCustomerEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelCustomerEmbeddedToJSONTyped(value?: PagedModelEntityModelCustomerEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customers': value['customers'] == null ? undefined : ((value['customers'] as Array<any>).map(EntityModelCustomerToJSON)),
    };
}

