/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelConfigurationHall } from './EntityModelConfigurationHall';
import {
    EntityModelConfigurationHallFromJSON,
    EntityModelConfigurationHallFromJSONTyped,
    EntityModelConfigurationHallToJSON,
    EntityModelConfigurationHallToJSONTyped,
} from './EntityModelConfigurationHall';

/**
 * 
 * @export
 * @interface PagedModelEntityModelConfigurationHallEmbedded
 */
export interface PagedModelEntityModelConfigurationHallEmbedded {
    /**
     * 
     * @type {Array<EntityModelConfigurationHall>}
     * @memberof PagedModelEntityModelConfigurationHallEmbedded
     */
    configurationHalls?: Array<EntityModelConfigurationHall>;
}

/**
 * Check if a given object implements the PagedModelEntityModelConfigurationHallEmbedded interface.
 */
export function instanceOfPagedModelEntityModelConfigurationHallEmbedded(value: object): value is PagedModelEntityModelConfigurationHallEmbedded {
    return true;
}

export function PagedModelEntityModelConfigurationHallEmbeddedFromJSON(json: any): PagedModelEntityModelConfigurationHallEmbedded {
    return PagedModelEntityModelConfigurationHallEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelConfigurationHallEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelConfigurationHallEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'configurationHalls': json['configurationHalls'] == null ? undefined : ((json['configurationHalls'] as Array<any>).map(EntityModelConfigurationHallFromJSON)),
    };
}

export function PagedModelEntityModelConfigurationHallEmbeddedToJSON(json: any): PagedModelEntityModelConfigurationHallEmbedded {
    return PagedModelEntityModelConfigurationHallEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelConfigurationHallEmbeddedToJSONTyped(value?: PagedModelEntityModelConfigurationHallEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configurationHalls': value['configurationHalls'] == null ? undefined : ((value['configurationHalls'] as Array<any>).map(EntityModelConfigurationHallToJSON)),
    };
}

