/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelCategorySpatial } from './EntityModelCategorySpatial';
import {
    EntityModelCategorySpatialFromJSON,
    EntityModelCategorySpatialFromJSONTyped,
    EntityModelCategorySpatialToJSON,
    EntityModelCategorySpatialToJSONTyped,
} from './EntityModelCategorySpatial';

/**
 * 
 * @export
 * @interface PagedModelEntityModelCategorySpatialEmbedded
 */
export interface PagedModelEntityModelCategorySpatialEmbedded {
    /**
     * 
     * @type {Array<EntityModelCategorySpatial>}
     * @memberof PagedModelEntityModelCategorySpatialEmbedded
     */
    categorySpatials?: Array<EntityModelCategorySpatial>;
}

/**
 * Check if a given object implements the PagedModelEntityModelCategorySpatialEmbedded interface.
 */
export function instanceOfPagedModelEntityModelCategorySpatialEmbedded(value: object): value is PagedModelEntityModelCategorySpatialEmbedded {
    return true;
}

export function PagedModelEntityModelCategorySpatialEmbeddedFromJSON(json: any): PagedModelEntityModelCategorySpatialEmbedded {
    return PagedModelEntityModelCategorySpatialEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelCategorySpatialEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelCategorySpatialEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'categorySpatials': json['categorySpatials'] == null ? undefined : ((json['categorySpatials'] as Array<any>).map(EntityModelCategorySpatialFromJSON)),
    };
}

export function PagedModelEntityModelCategorySpatialEmbeddedToJSON(json: any): PagedModelEntityModelCategorySpatialEmbedded {
    return PagedModelEntityModelCategorySpatialEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelCategorySpatialEmbeddedToJSONTyped(value?: PagedModelEntityModelCategorySpatialEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categorySpatials': value['categorySpatials'] == null ? undefined : ((value['categorySpatials'] as Array<any>).map(EntityModelCategorySpatialToJSON)),
    };
}

