/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { PagedModelEntityModelBookingEmbedded } from './PagedModelEntityModelBookingEmbedded';
import {
    PagedModelEntityModelBookingEmbeddedFromJSON,
    PagedModelEntityModelBookingEmbeddedFromJSONTyped,
    PagedModelEntityModelBookingEmbeddedToJSON,
    PagedModelEntityModelBookingEmbeddedToJSONTyped,
} from './PagedModelEntityModelBookingEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface PagedModelEntityModelBooking
 */
export interface PagedModelEntityModelBooking {
    /**
     * 
     * @type {PagedModelEntityModelBookingEmbedded}
     * @memberof PagedModelEntityModelBooking
     */
    embedded?: PagedModelEntityModelBookingEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelBooking
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelBooking
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelBooking interface.
 */
export function instanceOfPagedModelEntityModelBooking(value: object): value is PagedModelEntityModelBooking {
    return true;
}

export function PagedModelEntityModelBookingFromJSON(json: any): PagedModelEntityModelBooking {
    return PagedModelEntityModelBookingFromJSONTyped(json, false);
}

export function PagedModelEntityModelBookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelBooking {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelBookingEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelBookingToJSON(json: any): PagedModelEntityModelBooking {
    return PagedModelEntityModelBookingToJSONTyped(json, false);
}

export function PagedModelEntityModelBookingToJSONTyped(value?: PagedModelEntityModelBooking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelBookingEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

