/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { PagedModelEntityModelPaymentStatusEmbedded } from './PagedModelEntityModelPaymentStatusEmbedded';
import {
    PagedModelEntityModelPaymentStatusEmbeddedFromJSON,
    PagedModelEntityModelPaymentStatusEmbeddedFromJSONTyped,
    PagedModelEntityModelPaymentStatusEmbeddedToJSON,
    PagedModelEntityModelPaymentStatusEmbeddedToJSONTyped,
} from './PagedModelEntityModelPaymentStatusEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface PagedModelEntityModelPaymentStatus
 */
export interface PagedModelEntityModelPaymentStatus {
    /**
     * 
     * @type {PagedModelEntityModelPaymentStatusEmbedded}
     * @memberof PagedModelEntityModelPaymentStatus
     */
    embedded?: PagedModelEntityModelPaymentStatusEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelPaymentStatus
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelPaymentStatus
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelPaymentStatus interface.
 */
export function instanceOfPagedModelEntityModelPaymentStatus(value: object): value is PagedModelEntityModelPaymentStatus {
    return true;
}

export function PagedModelEntityModelPaymentStatusFromJSON(json: any): PagedModelEntityModelPaymentStatus {
    return PagedModelEntityModelPaymentStatusFromJSONTyped(json, false);
}

export function PagedModelEntityModelPaymentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelPaymentStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelPaymentStatusEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelPaymentStatusToJSON(json: any): PagedModelEntityModelPaymentStatus {
    return PagedModelEntityModelPaymentStatusToJSONTyped(json, false);
}

export function PagedModelEntityModelPaymentStatusToJSONTyped(value?: PagedModelEntityModelPaymentStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelPaymentStatusEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

