/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelPaymentStatus } from './EntityModelPaymentStatus';
import {
    EntityModelPaymentStatusFromJSON,
    EntityModelPaymentStatusFromJSONTyped,
    EntityModelPaymentStatusToJSON,
    EntityModelPaymentStatusToJSONTyped,
} from './EntityModelPaymentStatus';

/**
 * 
 * @export
 * @interface PagedModelEntityModelPaymentStatusEmbedded
 */
export interface PagedModelEntityModelPaymentStatusEmbedded {
    /**
     * 
     * @type {Array<EntityModelPaymentStatus>}
     * @memberof PagedModelEntityModelPaymentStatusEmbedded
     */
    paymentStatuses?: Array<EntityModelPaymentStatus>;
}

/**
 * Check if a given object implements the PagedModelEntityModelPaymentStatusEmbedded interface.
 */
export function instanceOfPagedModelEntityModelPaymentStatusEmbedded(value: object): value is PagedModelEntityModelPaymentStatusEmbedded {
    return true;
}

export function PagedModelEntityModelPaymentStatusEmbeddedFromJSON(json: any): PagedModelEntityModelPaymentStatusEmbedded {
    return PagedModelEntityModelPaymentStatusEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelPaymentStatusEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelPaymentStatusEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentStatuses': json['paymentStatuses'] == null ? undefined : ((json['paymentStatuses'] as Array<any>).map(EntityModelPaymentStatusFromJSON)),
    };
}

export function PagedModelEntityModelPaymentStatusEmbeddedToJSON(json: any): PagedModelEntityModelPaymentStatusEmbedded {
    return PagedModelEntityModelPaymentStatusEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelPaymentStatusEmbeddedToJSONTyped(value?: PagedModelEntityModelPaymentStatusEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentStatuses': value['paymentStatuses'] == null ? undefined : ((value['paymentStatuses'] as Array<any>).map(EntityModelPaymentStatusToJSON)),
    };
}

