/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelSeatStatus } from './EntityModelSeatStatus';
import {
    EntityModelSeatStatusFromJSON,
    EntityModelSeatStatusFromJSONTyped,
    EntityModelSeatStatusToJSON,
    EntityModelSeatStatusToJSONTyped,
} from './EntityModelSeatStatus';

/**
 * 
 * @export
 * @interface PagedModelEntityModelSeatStatusEmbedded
 */
export interface PagedModelEntityModelSeatStatusEmbedded {
    /**
     * 
     * @type {Array<EntityModelSeatStatus>}
     * @memberof PagedModelEntityModelSeatStatusEmbedded
     */
    seatStatuses?: Array<EntityModelSeatStatus>;
}

/**
 * Check if a given object implements the PagedModelEntityModelSeatStatusEmbedded interface.
 */
export function instanceOfPagedModelEntityModelSeatStatusEmbedded(value: object): value is PagedModelEntityModelSeatStatusEmbedded {
    return true;
}

export function PagedModelEntityModelSeatStatusEmbeddedFromJSON(json: any): PagedModelEntityModelSeatStatusEmbedded {
    return PagedModelEntityModelSeatStatusEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelSeatStatusEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelSeatStatusEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'seatStatuses': json['seatStatuses'] == null ? undefined : ((json['seatStatuses'] as Array<any>).map(EntityModelSeatStatusFromJSON)),
    };
}

export function PagedModelEntityModelSeatStatusEmbeddedToJSON(json: any): PagedModelEntityModelSeatStatusEmbedded {
    return PagedModelEntityModelSeatStatusEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelSeatStatusEmbeddedToJSONTyped(value?: PagedModelEntityModelSeatStatusEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seatStatuses': value['seatStatuses'] == null ? undefined : ((value['seatStatuses'] as Array<any>).map(EntityModelSeatStatusToJSON)),
    };
}

