/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { PagedModelEntityModelCategorySpatialEmbedded } from './PagedModelEntityModelCategorySpatialEmbedded';
import {
    PagedModelEntityModelCategorySpatialEmbeddedFromJSON,
    PagedModelEntityModelCategorySpatialEmbeddedFromJSONTyped,
    PagedModelEntityModelCategorySpatialEmbeddedToJSON,
    PagedModelEntityModelCategorySpatialEmbeddedToJSONTyped,
} from './PagedModelEntityModelCategorySpatialEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface PagedModelEntityModelCategorySpatial
 */
export interface PagedModelEntityModelCategorySpatial {
    /**
     * 
     * @type {PagedModelEntityModelCategorySpatialEmbedded}
     * @memberof PagedModelEntityModelCategorySpatial
     */
    embedded?: PagedModelEntityModelCategorySpatialEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelCategorySpatial
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelCategorySpatial
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelCategorySpatial interface.
 */
export function instanceOfPagedModelEntityModelCategorySpatial(value: object): value is PagedModelEntityModelCategorySpatial {
    return true;
}

export function PagedModelEntityModelCategorySpatialFromJSON(json: any): PagedModelEntityModelCategorySpatial {
    return PagedModelEntityModelCategorySpatialFromJSONTyped(json, false);
}

export function PagedModelEntityModelCategorySpatialFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelCategorySpatial {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelCategorySpatialEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelCategorySpatialToJSON(json: any): PagedModelEntityModelCategorySpatial {
    return PagedModelEntityModelCategorySpatialToJSONTyped(json, false);
}

export function PagedModelEntityModelCategorySpatialToJSONTyped(value?: PagedModelEntityModelCategorySpatial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelCategorySpatialEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

