/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { PagedModelEntityModelTarificationEmbedded } from './PagedModelEntityModelTarificationEmbedded';
import {
    PagedModelEntityModelTarificationEmbeddedFromJSON,
    PagedModelEntityModelTarificationEmbeddedFromJSONTyped,
    PagedModelEntityModelTarificationEmbeddedToJSON,
    PagedModelEntityModelTarificationEmbeddedToJSONTyped,
} from './PagedModelEntityModelTarificationEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface PagedModelEntityModelTarification
 */
export interface PagedModelEntityModelTarification {
    /**
     * 
     * @type {PagedModelEntityModelTarificationEmbedded}
     * @memberof PagedModelEntityModelTarification
     */
    embedded?: PagedModelEntityModelTarificationEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelTarification
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelTarification
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelTarification interface.
 */
export function instanceOfPagedModelEntityModelTarification(value: object): value is PagedModelEntityModelTarification {
    return true;
}

export function PagedModelEntityModelTarificationFromJSON(json: any): PagedModelEntityModelTarification {
    return PagedModelEntityModelTarificationFromJSONTyped(json, false);
}

export function PagedModelEntityModelTarificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelTarification {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelTarificationEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelTarificationToJSON(json: any): PagedModelEntityModelTarification {
    return PagedModelEntityModelTarificationToJSONTyped(json, false);
}

export function PagedModelEntityModelTarificationToJSONTyped(value?: PagedModelEntityModelTarification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelTarificationEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

