/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { PagedModelEntityModelPaymentEmbedded } from './PagedModelEntityModelPaymentEmbedded';
import {
    PagedModelEntityModelPaymentEmbeddedFromJSON,
    PagedModelEntityModelPaymentEmbeddedFromJSONTyped,
    PagedModelEntityModelPaymentEmbeddedToJSON,
    PagedModelEntityModelPaymentEmbeddedToJSONTyped,
} from './PagedModelEntityModelPaymentEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface PagedModelEntityModelPayment
 */
export interface PagedModelEntityModelPayment {
    /**
     * 
     * @type {PagedModelEntityModelPaymentEmbedded}
     * @memberof PagedModelEntityModelPayment
     */
    embedded?: PagedModelEntityModelPaymentEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelPayment
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelPayment
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelPayment interface.
 */
export function instanceOfPagedModelEntityModelPayment(value: object): value is PagedModelEntityModelPayment {
    return true;
}

export function PagedModelEntityModelPaymentFromJSON(json: any): PagedModelEntityModelPayment {
    return PagedModelEntityModelPaymentFromJSONTyped(json, false);
}

export function PagedModelEntityModelPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelPayment {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelPaymentEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelPaymentToJSON(json: any): PagedModelEntityModelPayment {
    return PagedModelEntityModelPaymentToJSONTyped(json, false);
}

export function PagedModelEntityModelPaymentToJSONTyped(value?: PagedModelEntityModelPayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelPaymentEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

