/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentStatusDTO
 */
export interface PaymentStatusDTO {
    /**
     * 
     * @type {number}
     * @memberof PaymentStatusDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentStatusDTO
     */
    paymentStatusName?: string;
}

/**
 * Check if a given object implements the PaymentStatusDTO interface.
 */
export function instanceOfPaymentStatusDTO(value: object): value is PaymentStatusDTO {
    return true;
}

export function PaymentStatusDTOFromJSON(json: any): PaymentStatusDTO {
    return PaymentStatusDTOFromJSONTyped(json, false);
}

export function PaymentStatusDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentStatusDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'paymentStatusName': json['paymentStatusName'] == null ? undefined : json['paymentStatusName'],
    };
}

export function PaymentStatusDTOToJSON(json: any): PaymentStatusDTO {
    return PaymentStatusDTOToJSONTyped(json, false);
}

export function PaymentStatusDTOToJSONTyped(value?: PaymentStatusDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'paymentStatusName': value['paymentStatusName'],
    };
}

