/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentRequestBody
 */
export interface PaymentRequestBody {
    /**
     * 
     * @type {number}
     * @memberof PaymentRequestBody
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PaymentRequestBody
     */
    paymentDateTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestBody
     */
    booking?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestBody
     */
    paymentStatus?: string;
}

/**
 * Check if a given object implements the PaymentRequestBody interface.
 */
export function instanceOfPaymentRequestBody(value: object): value is PaymentRequestBody {
    return true;
}

export function PaymentRequestBodyFromJSON(json: any): PaymentRequestBody {
    return PaymentRequestBodyFromJSONTyped(json, false);
}

export function PaymentRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'paymentDateTime': json['paymentDateTime'] == null ? undefined : (new Date(json['paymentDateTime'])),
        'booking': json['booking'] == null ? undefined : json['booking'],
        'paymentStatus': json['paymentStatus'] == null ? undefined : json['paymentStatus'],
    };
}

export function PaymentRequestBodyToJSON(json: any): PaymentRequestBody {
    return PaymentRequestBodyToJSONTyped(json, false);
}

export function PaymentRequestBodyToJSONTyped(value?: PaymentRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'paymentDateTime': value['paymentDateTime'] == null ? undefined : ((value['paymentDateTime']).toISOString()),
        'booking': value['booking'],
        'paymentStatus': value['paymentStatus'],
    };
}

