/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentStatusDTO } from './PaymentStatusDTO';
import {
    PaymentStatusDTOFromJSON,
    PaymentStatusDTOFromJSONTyped,
    PaymentStatusDTOToJSON,
    PaymentStatusDTOToJSONTyped,
} from './PaymentStatusDTO';
import type { BookingDTO } from './BookingDTO';
import {
    BookingDTOFromJSON,
    BookingDTOFromJSONTyped,
    BookingDTOToJSON,
    BookingDTOToJSONTyped,
} from './BookingDTO';

/**
 * 
 * @export
 * @interface PaymentDTO
 */
export interface PaymentDTO {
    /**
     * 
     * @type {number}
     * @memberof PaymentDTO
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PaymentDTO
     */
    paymentDateTime?: Date;
    /**
     * 
     * @type {BookingDTO}
     * @memberof PaymentDTO
     */
    booking?: BookingDTO;
    /**
     * 
     * @type {PaymentStatusDTO}
     * @memberof PaymentDTO
     */
    paymentStatus?: PaymentStatusDTO;
}

/**
 * Check if a given object implements the PaymentDTO interface.
 */
export function instanceOfPaymentDTO(value: object): value is PaymentDTO {
    return true;
}

export function PaymentDTOFromJSON(json: any): PaymentDTO {
    return PaymentDTOFromJSONTyped(json, false);
}

export function PaymentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'paymentDateTime': json['paymentDateTime'] == null ? undefined : (new Date(json['paymentDateTime'])),
        'booking': json['booking'] == null ? undefined : BookingDTOFromJSON(json['booking']),
        'paymentStatus': json['paymentStatus'] == null ? undefined : PaymentStatusDTOFromJSON(json['paymentStatus']),
    };
}

export function PaymentDTOToJSON(json: any): PaymentDTO {
    return PaymentDTOToJSONTyped(json, false);
}

export function PaymentDTOToJSONTyped(value?: PaymentDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'paymentDateTime': value['paymentDateTime'] == null ? undefined : ((value['paymentDateTime']).toISOString()),
        'booking': BookingDTOToJSON(value['booking']),
        'paymentStatus': PaymentStatusDTOToJSON(value['paymentStatus']),
    };
}

