/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeatStatusRequestBody
 */
export interface SeatStatusRequestBody {
    /**
     * 
     * @type {number}
     * @memberof SeatStatusRequestBody
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SeatStatusRequestBody
     */
    name?: string;
}

/**
 * Check if a given object implements the SeatStatusRequestBody interface.
 */
export function instanceOfSeatStatusRequestBody(value: object): value is SeatStatusRequestBody {
    return true;
}

export function SeatStatusRequestBodyFromJSON(json: any): SeatStatusRequestBody {
    return SeatStatusRequestBodyFromJSONTyped(json, false);
}

export function SeatStatusRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeatStatusRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SeatStatusRequestBodyToJSON(json: any): SeatStatusRequestBody {
    return SeatStatusRequestBodyToJSONTyped(json, false);
}

export function SeatStatusRequestBodyToJSONTyped(value?: SeatStatusRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

