/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeatRequestBody
 */
export interface SeatRequestBody {
    /**
     * 
     * @type {number}
     * @memberof SeatRequestBody
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SeatRequestBody
     */
    isSeated?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SeatRequestBody
     */
    rowNo?: string;
    /**
     * 
     * @type {number}
     * @memberof SeatRequestBody
     */
    seatNo?: number;
    /**
     * 
     * @type {string}
     * @memberof SeatRequestBody
     */
    configurationHall?: string;
    /**
     * 
     * @type {string}
     * @memberof SeatRequestBody
     */
    categorySpatial?: string;
    /**
     * 
     * @type {string}
     * @memberof SeatRequestBody
     */
    categoryTariff?: string;
    /**
     * 
     * @type {string}
     * @memberof SeatRequestBody
     */
    seatStatus?: string;
}

/**
 * Check if a given object implements the SeatRequestBody interface.
 */
export function instanceOfSeatRequestBody(value: object): value is SeatRequestBody {
    return true;
}

export function SeatRequestBodyFromJSON(json: any): SeatRequestBody {
    return SeatRequestBodyFromJSONTyped(json, false);
}

export function SeatRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeatRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'isSeated': json['isSeated'] == null ? undefined : json['isSeated'],
        'rowNo': json['rowNo'] == null ? undefined : json['rowNo'],
        'seatNo': json['seatNo'] == null ? undefined : json['seatNo'],
        'configurationHall': json['configurationHall'] == null ? undefined : json['configurationHall'],
        'categorySpatial': json['categorySpatial'] == null ? undefined : json['categorySpatial'],
        'categoryTariff': json['categoryTariff'] == null ? undefined : json['categoryTariff'],
        'seatStatus': json['seatStatus'] == null ? undefined : json['seatStatus'],
    };
}

export function SeatRequestBodyToJSON(json: any): SeatRequestBody {
    return SeatRequestBodyToJSONTyped(json, false);
}

export function SeatRequestBodyToJSONTyped(value?: SeatRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'isSeated': value['isSeated'],
        'rowNo': value['rowNo'],
        'seatNo': value['seatNo'],
        'configurationHall': value['configurationHall'],
        'categorySpatial': value['categorySpatial'],
        'categoryTariff': value['categoryTariff'],
        'seatStatus': value['seatStatus'],
    };
}

