/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionEventRequestBody
 */
export interface SessionEventRequestBody {
    /**
     * 
     * @type {number}
     * @memberof SessionEventRequestBody
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof SessionEventRequestBody
     */
    dateAndTimeStartSessionEvent?: Date;
    /**
     * 
     * @type {number}
     * @memberof SessionEventRequestBody
     */
    durationInMinutes?: number;
    /**
     * 
     * @type {Date}
     * @memberof SessionEventRequestBody
     */
    dateAndTimeEndSessionEvent?: Date;
    /**
     * 
     * @type {string}
     * @memberof SessionEventRequestBody
     */
    event?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionEventRequestBody
     */
    configurationHall?: string;
}

/**
 * Check if a given object implements the SessionEventRequestBody interface.
 */
export function instanceOfSessionEventRequestBody(value: object): value is SessionEventRequestBody {
    return true;
}

export function SessionEventRequestBodyFromJSON(json: any): SessionEventRequestBody {
    return SessionEventRequestBodyFromJSONTyped(json, false);
}

export function SessionEventRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionEventRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'dateAndTimeStartSessionEvent': json['dateAndTimeStartSessionEvent'] == null ? undefined : (new Date(json['dateAndTimeStartSessionEvent'])),
        'durationInMinutes': json['durationInMinutes'] == null ? undefined : json['durationInMinutes'],
        'dateAndTimeEndSessionEvent': json['dateAndTimeEndSessionEvent'] == null ? undefined : (new Date(json['dateAndTimeEndSessionEvent'])),
        'event': json['event'] == null ? undefined : json['event'],
        'configurationHall': json['configurationHall'] == null ? undefined : json['configurationHall'],
    };
}

export function SessionEventRequestBodyToJSON(json: any): SessionEventRequestBody {
    return SessionEventRequestBodyToJSONTyped(json, false);
}

export function SessionEventRequestBodyToJSONTyped(value?: SessionEventRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'dateAndTimeStartSessionEvent': value['dateAndTimeStartSessionEvent'] == null ? undefined : ((value['dateAndTimeStartSessionEvent']).toISOString()),
        'durationInMinutes': value['durationInMinutes'],
        'dateAndTimeEndSessionEvent': value['dateAndTimeEndSessionEvent'] == null ? undefined : ((value['dateAndTimeEndSessionEvent']).toISOString()),
        'event': value['event'],
        'configurationHall': value['configurationHall'],
    };
}

