/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigurationHall } from './ConfigurationHall';
import {
    ConfigurationHallFromJSON,
    ConfigurationHallFromJSONTyped,
    ConfigurationHallToJSON,
    ConfigurationHallToJSONTyped,
} from './ConfigurationHall';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';

/**
 * 
 * @export
 * @interface SessionEvent
 */
export interface SessionEvent {
    /**
     * 
     * @type {number}
     * @memberof SessionEvent
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof SessionEvent
     */
    dateAndTimeStartSessionEvent?: Date;
    /**
     * 
     * @type {number}
     * @memberof SessionEvent
     */
    durationInMinutes?: number;
    /**
     * 
     * @type {Date}
     * @memberof SessionEvent
     */
    dateAndTimeEndSessionEvent?: Date;
    /**
     * 
     * @type {Event}
     * @memberof SessionEvent
     */
    event?: Event;
    /**
     * 
     * @type {ConfigurationHall}
     * @memberof SessionEvent
     */
    configurationHall?: ConfigurationHall;
}

/**
 * Check if a given object implements the SessionEvent interface.
 */
export function instanceOfSessionEvent(value: object): value is SessionEvent {
    return true;
}

export function SessionEventFromJSON(json: any): SessionEvent {
    return SessionEventFromJSONTyped(json, false);
}

export function SessionEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'dateAndTimeStartSessionEvent': json['dateAndTimeStartSessionEvent'] == null ? undefined : (new Date(json['dateAndTimeStartSessionEvent'])),
        'durationInMinutes': json['durationInMinutes'] == null ? undefined : json['durationInMinutes'],
        'dateAndTimeEndSessionEvent': json['dateAndTimeEndSessionEvent'] == null ? undefined : (new Date(json['dateAndTimeEndSessionEvent'])),
        'event': json['event'] == null ? undefined : EventFromJSON(json['event']),
        'configurationHall': json['configurationHall'] == null ? undefined : ConfigurationHallFromJSON(json['configurationHall']),
    };
}

export function SessionEventToJSON(json: any): SessionEvent {
    return SessionEventToJSONTyped(json, false);
}

export function SessionEventToJSONTyped(value?: SessionEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'dateAndTimeStartSessionEvent': value['dateAndTimeStartSessionEvent'] == null ? undefined : ((value['dateAndTimeStartSessionEvent']).toISOString()),
        'durationInMinutes': value['durationInMinutes'],
        'dateAndTimeEndSessionEvent': value['dateAndTimeEndSessionEvent'] == null ? undefined : ((value['dateAndTimeEndSessionEvent']).toISOString()),
        'event': EventToJSON(value['event']),
        'configurationHall': ConfigurationHallToJSON(value['configurationHall']),
    };
}

