/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigurationHallDTO } from './ConfigurationHallDTO';
import {
    ConfigurationHallDTOFromJSON,
    ConfigurationHallDTOFromJSONTyped,
    ConfigurationHallDTOToJSON,
    ConfigurationHallDTOToJSONTyped,
} from './ConfigurationHallDTO';
import type { EventDTO } from './EventDTO';
import {
    EventDTOFromJSON,
    EventDTOFromJSONTyped,
    EventDTOToJSON,
    EventDTOToJSONTyped,
} from './EventDTO';

/**
 * 
 * @export
 * @interface SessionEventDTO
 */
export interface SessionEventDTO {
    /**
     * 
     * @type {number}
     * @memberof SessionEventDTO
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof SessionEventDTO
     */
    dateAndTimeStartSessionEvent?: Date;
    /**
     * 
     * @type {number}
     * @memberof SessionEventDTO
     */
    durationInMinutes?: number;
    /**
     * 
     * @type {EventDTO}
     * @memberof SessionEventDTO
     */
    event?: EventDTO;
    /**
     * 
     * @type {ConfigurationHallDTO}
     * @memberof SessionEventDTO
     */
    configurationHall?: ConfigurationHallDTO;
}

/**
 * Check if a given object implements the SessionEventDTO interface.
 */
export function instanceOfSessionEventDTO(value: object): value is SessionEventDTO {
    return true;
}

export function SessionEventDTOFromJSON(json: any): SessionEventDTO {
    return SessionEventDTOFromJSONTyped(json, false);
}

export function SessionEventDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionEventDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'dateAndTimeStartSessionEvent': json['dateAndTimeStartSessionEvent'] == null ? undefined : (new Date(json['dateAndTimeStartSessionEvent'])),
        'durationInMinutes': json['durationInMinutes'] == null ? undefined : json['durationInMinutes'],
        'event': json['event'] == null ? undefined : EventDTOFromJSON(json['event']),
        'configurationHall': json['configurationHall'] == null ? undefined : ConfigurationHallDTOFromJSON(json['configurationHall']),
    };
}

export function SessionEventDTOToJSON(json: any): SessionEventDTO {
    return SessionEventDTOToJSONTyped(json, false);
}

export function SessionEventDTOToJSONTyped(value?: SessionEventDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'dateAndTimeStartSessionEvent': value['dateAndTimeStartSessionEvent'] == null ? undefined : ((value['dateAndTimeStartSessionEvent']).toISOString()),
        'durationInMinutes': value['durationInMinutes'],
        'event': EventDTOToJSON(value['event']),
        'configurationHall': ConfigurationHallDTOToJSON(value['configurationHall']),
    };
}

