/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';

/**
 * 
 * @export
 * @interface Tarification
 */
export interface Tarification {
    /**
     * 
     * @type {number}
     * @memberof Tarification
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Tarification
     */
    basePrice?: number;
    /**
     * 
     * @type {number}
     * @memberof Tarification
     */
    taxeRate?: number;
    /**
     * 
     * @type {number}
     * @memberof Tarification
     */
    discountStudentRate?: number;
    /**
     * 
     * @type {number}
     * @memberof Tarification
     */
    discountSeniorRate?: number;
    /**
     * 
     * @type {number}
     * @memberof Tarification
     */
    discountChildRate?: number;
    /**
     * 
     * @type {number}
     * @memberof Tarification
     */
    discountUnemployedRate?: number;
    /**
     * 
     * @type {Event}
     * @memberof Tarification
     */
    event?: Event;
}

/**
 * Check if a given object implements the Tarification interface.
 */
export function instanceOfTarification(value: object): value is Tarification {
    return true;
}

export function TarificationFromJSON(json: any): Tarification {
    return TarificationFromJSONTyped(json, false);
}

export function TarificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tarification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'basePrice': json['basePrice'] == null ? undefined : json['basePrice'],
        'taxeRate': json['taxeRate'] == null ? undefined : json['taxeRate'],
        'discountStudentRate': json['discountStudentRate'] == null ? undefined : json['discountStudentRate'],
        'discountSeniorRate': json['discountSeniorRate'] == null ? undefined : json['discountSeniorRate'],
        'discountChildRate': json['discountChildRate'] == null ? undefined : json['discountChildRate'],
        'discountUnemployedRate': json['discountUnemployedRate'] == null ? undefined : json['discountUnemployedRate'],
        'event': json['event'] == null ? undefined : EventFromJSON(json['event']),
    };
}

export function TarificationToJSON(json: any): Tarification {
    return TarificationToJSONTyped(json, false);
}

export function TarificationToJSONTyped(value?: Tarification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'basePrice': value['basePrice'],
        'taxeRate': value['taxeRate'],
        'discountStudentRate': value['discountStudentRate'],
        'discountSeniorRate': value['discountSeniorRate'],
        'discountChildRate': value['discountChildRate'],
        'discountUnemployedRate': value['discountUnemployedRate'],
        'event': EventToJSON(value['event']),
    };
}

