/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TarificationRequestBody
 */
export interface TarificationRequestBody {
    /**
     * 
     * @type {number}
     * @memberof TarificationRequestBody
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TarificationRequestBody
     */
    basePrice?: number;
    /**
     * 
     * @type {number}
     * @memberof TarificationRequestBody
     */
    taxeRate?: number;
    /**
     * 
     * @type {number}
     * @memberof TarificationRequestBody
     */
    discountStudentRate?: number;
    /**
     * 
     * @type {number}
     * @memberof TarificationRequestBody
     */
    discountSeniorRate?: number;
    /**
     * 
     * @type {number}
     * @memberof TarificationRequestBody
     */
    discountChildRate?: number;
    /**
     * 
     * @type {number}
     * @memberof TarificationRequestBody
     */
    discountUnemployedRate?: number;
    /**
     * 
     * @type {string}
     * @memberof TarificationRequestBody
     */
    event?: string;
}

/**
 * Check if a given object implements the TarificationRequestBody interface.
 */
export function instanceOfTarificationRequestBody(value: object): value is TarificationRequestBody {
    return true;
}

export function TarificationRequestBodyFromJSON(json: any): TarificationRequestBody {
    return TarificationRequestBodyFromJSONTyped(json, false);
}

export function TarificationRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TarificationRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'basePrice': json['basePrice'] == null ? undefined : json['basePrice'],
        'taxeRate': json['taxeRate'] == null ? undefined : json['taxeRate'],
        'discountStudentRate': json['discountStudentRate'] == null ? undefined : json['discountStudentRate'],
        'discountSeniorRate': json['discountSeniorRate'] == null ? undefined : json['discountSeniorRate'],
        'discountChildRate': json['discountChildRate'] == null ? undefined : json['discountChildRate'],
        'discountUnemployedRate': json['discountUnemployedRate'] == null ? undefined : json['discountUnemployedRate'],
        'event': json['event'] == null ? undefined : json['event'],
    };
}

export function TarificationRequestBodyToJSON(json: any): TarificationRequestBody {
    return TarificationRequestBodyToJSONTyped(json, false);
}

export function TarificationRequestBodyToJSONTyped(value?: TarificationRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'basePrice': value['basePrice'],
        'taxeRate': value['taxeRate'],
        'discountStudentRate': value['discountStudentRate'],
        'discountSeniorRate': value['discountSeniorRate'],
        'discountChildRate': value['discountChildRate'],
        'discountUnemployedRate': value['discountUnemployedRate'],
        'event': value['event'],
    };
}

