/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeatDTO } from './SeatDTO';
import {
    SeatDTOFromJSON,
    SeatDTOFromJSONTyped,
    SeatDTOToJSON,
    SeatDTOToJSONTyped,
} from './SeatDTO';
import type { SessionEventDTO } from './SessionEventDTO';
import {
    SessionEventDTOFromJSON,
    SessionEventDTOFromJSONTyped,
    SessionEventDTOToJSON,
    SessionEventDTOToJSONTyped,
} from './SessionEventDTO';

/**
 * 
 * @export
 * @interface TicketReservationKeyDTO
 */
export interface TicketReservationKeyDTO {
    /**
     * 
     * @type {SeatDTO}
     * @memberof TicketReservationKeyDTO
     */
    seatId?: SeatDTO;
    /**
     * 
     * @type {SessionEventDTO}
     * @memberof TicketReservationKeyDTO
     */
    sessionEventId?: SessionEventDTO;
}

/**
 * Check if a given object implements the TicketReservationKeyDTO interface.
 */
export function instanceOfTicketReservationKeyDTO(value: object): value is TicketReservationKeyDTO {
    return true;
}

export function TicketReservationKeyDTOFromJSON(json: any): TicketReservationKeyDTO {
    return TicketReservationKeyDTOFromJSONTyped(json, false);
}

export function TicketReservationKeyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketReservationKeyDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'seatId': json['seatId'] == null ? undefined : SeatDTOFromJSON(json['seatId']),
        'sessionEventId': json['sessionEventId'] == null ? undefined : SessionEventDTOFromJSON(json['sessionEventId']),
    };
}

export function TicketReservationKeyDTOToJSON(json: any): TicketReservationKeyDTO {
    return TicketReservationKeyDTOToJSONTyped(json, false);
}

export function TicketReservationKeyDTOToJSONTyped(value?: TicketReservationKeyDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seatId': SeatDTOToJSON(value['seatId']),
        'sessionEventId': SessionEventDTOToJSON(value['sessionEventId']),
    };
}

