/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketReservationKey } from './TicketReservationKey';
import {
    TicketReservationKeyFromJSON,
    TicketReservationKeyFromJSONTyped,
    TicketReservationKeyToJSON,
    TicketReservationKeyToJSONTyped,
} from './TicketReservationKey';

/**
 * 
 * @export
 * @interface TicketReservation
 */
export interface TicketReservation {
    /**
     * 
     * @type {TicketReservationKey}
     * @memberof TicketReservation
     */
    id?: TicketReservationKey;
    /**
     * 
     * @type {boolean}
     * @memberof TicketReservation
     */
    isBooked?: boolean;
}

/**
 * Check if a given object implements the TicketReservation interface.
 */
export function instanceOfTicketReservation(value: object): value is TicketReservation {
    return true;
}

export function TicketReservationFromJSON(json: any): TicketReservation {
    return TicketReservationFromJSONTyped(json, false);
}

export function TicketReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketReservation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : TicketReservationKeyFromJSON(json['id']),
        'isBooked': json['isBooked'] == null ? undefined : json['isBooked'],
    };
}

export function TicketReservationToJSON(json: any): TicketReservation {
    return TicketReservationToJSONTyped(json, false);
}

export function TicketReservationToJSONTyped(value?: TicketReservation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': TicketReservationKeyToJSON(value['id']),
        'isBooked': value['isBooked'],
    };
}

