/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmployeeDTO } from './EmployeeDTO';
import {
    EmployeeDTOFromJSON,
    EmployeeDTOFromJSONTyped,
    EmployeeDTOToJSON,
    EmployeeDTOToJSONTyped,
} from './EmployeeDTO';
import type { AddressDTO } from './AddressDTO';
import {
    AddressDTOFromJSON,
    AddressDTOFromJSONTyped,
    AddressDTOToJSON,
    AddressDTOToJSONTyped,
} from './AddressDTO';

/**
 * 
 * @export
 * @interface VenueDTO
 */
export interface VenueDTO {
    /**
     * 
     * @type {number}
     * @memberof VenueDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof VenueDTO
     */
    name: string;
    /**
     * 
     * @type {AddressDTO}
     * @memberof VenueDTO
     */
    address?: AddressDTO;
    /**
     * 
     * @type {Set<EmployeeDTO>}
     * @memberof VenueDTO
     */
    employees?: Set<EmployeeDTO>;
}

/**
 * Check if a given object implements the VenueDTO interface.
 */
export function instanceOfVenueDTO(value: object): value is VenueDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function VenueDTOFromJSON(json: any): VenueDTO {
    return VenueDTOFromJSONTyped(json, false);
}

export function VenueDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'address': json['address'] == null ? undefined : AddressDTOFromJSON(json['address']),
        'employees': json['employees'] == null ? undefined : (new Set((json['employees'] as Array<any>).map(EmployeeDTOFromJSON))),
    };
}

export function VenueDTOToJSON(json: any): VenueDTO {
    return VenueDTOToJSONTyped(json, false);
}

export function VenueDTOToJSONTyped(value?: VenueDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': AddressDTOToJSON(value['address']),
        'employees': value['employees'] == null ? undefined : (Array.from(value['employees'] as Set<any>).map(EmployeeDTOToJSON)),
    };
}

