/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * 
 * @export
 * @interface VenueRequestBody
 */
export interface VenueRequestBody {
    /**
     * 
     * @type {number}
     * @memberof VenueRequestBody
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof VenueRequestBody
     */
    name: string;
    /**
     * 
     * @type {Address}
     * @memberof VenueRequestBody
     */
    address?: Address;
    /**
     * 
     * @type {Array<string>}
     * @memberof VenueRequestBody
     */
    employees?: Array<string>;
}

/**
 * Check if a given object implements the VenueRequestBody interface.
 */
export function instanceOfVenueRequestBody(value: object): value is VenueRequestBody {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function VenueRequestBodyFromJSON(json: any): VenueRequestBody {
    return VenueRequestBodyFromJSONTyped(json, false);
}

export function VenueRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'employees': json['employees'] == null ? undefined : json['employees'],
    };
}

export function VenueRequestBodyToJSON(json: any): VenueRequestBody {
    return VenueRequestBodyToJSONTyped(json, false);
}

export function VenueRequestBodyToJSONTyped(value?: VenueRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': AddressToJSON(value['address']),
        'employees': value['employees'],
    };
}

