-- these are just to test that tunder request are correctly executed

-- Booking & seat status
SELECT SEAT.ID, SEAT.ROW_NO, SEAT.SEAT_NO, SEAT.SEAT_STATUS_FK, SEAT_STATUS.name 
FROM SEAT, SEAT_STATUS 
where (SEAT_STATUS_FK = SEAT_STATUS.id);

-- Payment & payment status
SELECT PAYMENT.id, PAYMENT_DATE_TIME, BOOKING_FK, PAYMENT_STATUS 
from PAYMENT, PAYMENT_STATUS_CATEGORY 


-- Booking with payment 
SELECT B.id bookingId, S.SEAT_NO, SS.name ,P.id PaymentId, PS.PAYMENT_STATUS
from BOOKING B, PAYMENT P, PAYMENT_STATUS_CATEGORY PS, SEAT S, SEAT_STATUS SS, TICKET_RESERVATION TR
where (B.id = P.BOOKING_FK) and (P.PAYMENT_STATUS_CATEGORY_FK = PS.id) and (B.id = TR.BOOKING_FK) and (TR.SEAT_ID = S.id) and (S.SEAT_STATUS_FK = SS.id);

-- All Booking with payment information
SELECT B.id AS bookingId, S.SEAT_NO, SS.name, P.id AS PaymentId, PS.PAYMENT_STATUS
FROM BOOKING B
INNER JOIN TICKET_RESERVATION TR ON B.id = TR.BOOKING_FK
INNER JOIN SEAT S ON TR.SEAT_ID = S.id
INNER JOIN SEAT_STATUS SS ON S.SEAT_STATUS_FK = SS.id
LEFT JOIN PAYMENT P ON B.id = P.BOOKING_FK
LEFT JOIN PAYMENT_STATUS_CATEGORY PS ON P.PAYMENT_STATUS_CATEGORY_FK = PS.id;

-- all these queries on the same page
SELECT B.id bookingId, S.SEAT_NO, SS.name seat_status ,P.id PaymentId, PS.PAYMENT_STATUS
from BOOKING B, PAYMENT P, PAYMENT_STATUS_CATEGORY PS, SEAT S, SEAT_STATUS SS, TICKET_RESERVATION TR
where (B.id = P.BOOKING_FK) and (P.PAYMENT_STATUS_CATEGORY_FK = PS.id) and (B.id = TR.BOOKING_FK) and (TR.SEAT_ID = S.id) and (S.SEAT_STATUS_FK = SS.id);
SELECT B.id AS bookingId, S.SEAT_NO, SS.name seat_status, P.id AS PaymentId, PS.PAYMENT_STATUS
FROM BOOKING B
INNER JOIN TICKET_RESERVATION TR ON B.id = TR.BOOKING_FK
INNER JOIN SEAT S ON TR.SEAT_ID = S.id
INNER JOIN SEAT_STATUS SS ON S.SEAT_STATUS_FK = SS.id
LEFT JOIN PAYMENT P ON B.id = P.BOOKING_FK
LEFT JOIN PAYMENT_STATUS_CATEGORY PS ON P.PAYMENT_STATUS_CATEGORY_FK = PS.id;
SELECT SEAT.ID, SEAT.ROW_NO, SEAT.SEAT_NO, SEAT.SEAT_STATUS_FK, SEAT_STATUS.name seat_status
FROM SEAT, SEAT_STATUS 
where (SEAT_STATUS_FK = SEAT_STATUS.id);
SELECT * FROM TICKET_RESERVATION ;
SELECT P.id, P.PAYMENT_DATE_TIME, P.BOOKING_FK, PAYMENT_STATUS_CATEGORY.PAYMENT_STATUS FROM PAYMENT P, PAYMENT_STATUS_CATEGORY;
